const screensOrder=['landing','email','rule','domain','decision','decisionConfirm','confidence','valentinOpen','caseCreated','d1intro','d1expect','d1assume','d1classify','d1control','d1summary','d2intro','d2agreement','d2dissect','d2cost','d2reflect','d2summary','d3intro','d3failures','d3uncomfortable','d3summary','d4intro','d4signals','d4rationalize','d4trigger','d4summary','d5intro','d5states','d5irreversible','d5sunk','d5redline','d5summary','d6intro','d6pros','d6counter','d6falsify','d6summary','d7intro','d7error','d7inaction','d7planb','d7decision','verdict','examIntro','examQuestions','examResult','completed','dangerMap','certificate','emailFinish'];
function fresh(){return{version:'production-stage-1',screen:'landing',resumeScreen:'',status:'new',sessionId:'',courseId:'COURSE-001',email:'',domain:'',decision:'',decisionPreset:'',initialConfidence:70,currentConfidence:70,confidenceHistory:[],expectedOutcome:'',expectedPreset:'',assumptions:[],assumptionTypes:{},control1:'',control1Preset:'',agreementWho:'',agreementWhoPreset:'',agreementSaid:'',agreementSaidPreset:'',agreementInference:'',agreementKnown:'',agreementCheck:'',trustCost:[],trustReflection:'',failureModes:[],uncomfortableFailure:'',uncomfortableWhy:'',signals:[],rationalizedSignal:'',rationalization:'',recheckTrigger:'',recheckPreset:'',greenState:'',yellowState:'',redLine:'',irreversible:[],sunkChoice:'',proArguments:'',counterArguments:'',falsificationFact:'',errorCost:'',inactionCost:'',planB:'',finalDecision:'',examQuestions:[],examPassed:false,dayResults:{},currentDay:0,events:[],startedAt:null,updatedAt:null,completedAt:null}}
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return Object.assign(fresh(),{screen:'recovery',status:'corrupt'})}}
let state=load();
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const norm=s=>String(s??'').trim().toLowerCase().replace(/\s+/g,' ');
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state))}
function go(screen){if(screen==='landing'&&state.screen!=='landing')state.resumeScreen=state.screen;state.screen=screen;save();render();scrollTo(0,0)}
function caseId(){if(!state.sessionId){state.sessionId=`DC-${new Date().getFullYear()}-${Math.floor(1000+Math.random()*9000)}`;save()}return state.sessionId}
function shell(inner){app.innerHTML=`<section class="screen"><div class="wrap">${inner}</div></section>`}
function valentinShell(inner){app.innerHTML=`<section class="valentin-beat"><div class="wrap">${inner}</div></section>`}
function btn(label,screen,kind=''){return `<button class="btn ${kind}" data-go="${screen}">${label}</button>`}
function back(screen){return `<button class="btn alt" data-go="${screen}">Назад</button>`}
function err(id){return `<div class="error" id="${id}" role="status" aria-live="polite"></div>`}
function valentin(text){return `<div class="valentin"><b>Валентин / вмешательство</b>${esc(text)}</div>`}
function optionCards(options,key,selected,custom=true){return `<div class="choice-grid">${options.map(o=>`<button class="choice ${selected===o?'selected':''}" data-single-key="${key}" data-single-value="${esc(o)}">${esc(o)}</button>`).join('')}${custom?`<button class="choice custom ${selected==='__custom'?'selected':''}" data-single-key="${key}" data-single-value="__custom">Свой вариант<small>Вписать и отредактировать</small></button>`:''}</div>`}
function editableSingle({key,presetKey,options,value,label='Можно поправить формулировку',placeholder='Уточните формулировку'}){return `${optionCards(options,presetKey,state[presetKey]||'')}<div class="editor"><label for="${key}">${label}</label><input id="${key}" type="text" value="${esc(value)}" placeholder="${esc(placeholder)}"></div>`}
function multiPicker({key,options,min,placeholder}){const arr=state[key]||[];return `<div class="choice-grid">${options.map(o=>`<button class="choice ${arr.some(x=>norm(x)===norm(o))?'selected':''}" data-multi-key="${key}" data-multi-value="${esc(o)}">${esc(o)}</button>`).join('')}<button class="choice custom" data-focus-custom="${key}">Свой вариант<small>Можно добавлять несколько своих</small></button></div><div class="multi-selected">${arr.map((x,i)=>`<div class="edit-row"><input type="text" data-edit-list="${key}" data-edit-index="${i}" value="${esc(x)}"><button data-del-list="${key}" data-del-index="${i}">×</button></div>`).join('')}</div><label for="${key}Custom">Свой вариант</label><div class="edit-row"><input id="${key}Custom" type="text" placeholder="${esc(placeholder||'Добавить свой вариант')}"><button data-add-custom="${key}">+</button></div><div class="counter">Нужно минимум: ${min}. Сейчас: ${arr.length}</div>`}
function textQuality(v,min=8){const n=norm(v);return !n?{ok:false,msg:'ОТВЕТА ПОКА НЕТ.'}:n.length<min?{ok:false,msg:'ПОКА СЛИШКОМ ОБЩО. ДОБАВЬТЕ КОНКРЕТИКУ.'}:{ok:true,msg:''}}
function prevResult(day){const r=state.dayResults['day'+(day-1)];return !r?'':`<div class="status-strip"><div><div class="eyebrow">Предыдущий день</div><div class="delta">${r.from}% → ${r.to}%</div></div><div><p><b>${esc(r.title)}</b></p><p>${esc(r.explanation)}</p></div></div>`}
function dayIntro(day,title,code,next){state.currentDay=day;save();shell(`${prevResult(day)}<div class="day-label">День ${day} / ${esc(code)}</div><h2>${esc(title)}</h2><p class="lead">${day===1?'Начинаем с того, на чём вообще стоит ваше решение.':'Старое дело остаётся открытым. Добавляем ещё один слой проверки.'}</p>${valentin(quotes['day'+day])}<div class="actions">${btn('Продолжить',next,'black')}</div>`)}
function setDayResult(day,to,title,explanation,details={}){const from=state.currentConfidence,next=clamp(Math.round(to),5,99);state.currentConfidence=next;state.confidenceHistory.push({stage:'day'+day,value:next,from});state.dayResults['day'+day]={from,to:next,delta:next-from,title,explanation,details};save()}
function computeDay1(){const vals=Object.values(state.assumptionTypes),known=vals.filter(x=>x==='ЗНАЮ').length,assumed=vals.filter(x=>x==='ПРЕДПОЛАГАЮ').length,said=vals.filter(x=>x==='МНЕ СКАЗАЛИ').length;const weights={data:4,past:2,written:3,trust:-2,intuition:-3,none:-6,__custom:0};const evidence=weights[state.control1Preset]??0,delta=clamp(known-assumed*2-said*3+evidence,-20,6);setDayResult(1,state.initialConfidence+delta,'Ожидание и предпосылки',`Из ${state.assumptions.length} предпосылок: знаю — ${known}, предполагаю — ${assumed}, мне сказали — ${said}. Основание решения тоже учтено в расчёте.`,{known,assumed,said,evidence})}
function computeDay2(){const impact={деньги:2,время:1,клиента:2,возможность:2,отношения:2,репутацию:3,'почти ничего':-1};const cost=state.trustCost.reduce((s,x)=>s+(impact[x]||1),0),verify=norm(state.agreementCheck).includes('пока никак')?-4:2,delta=clamp(-cost+verify,-14,4);setDayResult(2,state.currentConfidence+delta,'Обещания и проверка',`Цена невыполненного обещания отмечена в ${state.trustCost.length} категориях. Способ проверки ${verify>0?'задан':'пока слабый'}.`,{cost,verify})}
function computeDay3(){const delta=clamp(-Math.round(state.failureModes.length/3),-12,-3);setDayResult(3,state.currentConfidence+delta,'Premortem',`Вы назвали ${state.failureModes.length} способов провала и отдельно выбрали версию, которую хотелось бы считать маловероятной.`,{count:state.failureModes.length})}
function computeDay4(){const monitoring=state.signals.length>=5?3:0,rational=-3,trigger=textQuality(state.recheckTrigger,10).ok?2:0,delta=clamp(monitoring+rational+trigger,-5,5);setDayResult(4,state.currentConfidence+delta,'Слабые сигналы',`Есть ${state.signals.length} ранних сигналов и конкретная точка перепроверки. Наличие контроля может не снижать уверенность, если риск стал наблюдаемым.`,{monitoring,rational,trigger})}
function computeDay5(){const irreversiblePenalty=Math.min(8,state.irreversible.length*2),sunk=state.sunkChoice==='continue'?-4:2,red=textQuality(state.redLine,10).ok?2:0,delta=clamp(-irreversiblePenalty+sunk+red,-14,5);setDayResult(5,state.currentConfidence+delta,'Необратимость и красная линия',`Названы ${state.irreversible.length} труднообратимые потери. Красная линия и выбор после её срабатывания учтены.`,{irreversiblePenalty,sunk,red})}
function computeDay6(){const falsify=textQuality(state.falsificationFact,10).ok?3:-4,counter=textQuality(state.counterArguments,10).ok?1:0,delta=clamp(falsify+counter,-6,5);setDayResult(6,state.currentConfidence+delta,'Проверяемость гипотезы','У вашей версии теперь есть аргумент против и факт, который способен заставить вас передумать. Проверяемость иногда повышает расчётную уверенность.',{falsify,counter})}
function computeDay7(){const errorSeverity=/деньг|обязатель/.test(norm(state.errorCost))?-4:-2,inactionCounter=/почти ничего/.test(norm(state.inactionCost))?-2:2,plan=textQuality(state.planB,10).ok?3:0,delta=clamp(errorSeverity+inactionCounter+plan,-8,6);setDayResult(7,state.currentConfidence+delta,'Цена ошибки и Plan B','Расчёт учитывает цену ошибки, цену бездействия и наличие конкретного Plan B. Это не рекомендация — только структурная оценка ответов.',{errorSeverity,inactionCounter,plan})}
function summary(day,next){const r=state.dayResults['day'+day];shell(`<div class="eyebrow">День ${day} / результат</div><div class="result-hero"><div class="result-number">${r.from}%<br>→ ${r.to}%</div><div><h3>${esc(r.title)}</h3><p class="lead">${esc(r.explanation)}</p><div class="conf-note">Процент рассчитан автоматически по структуре ответов. AI не используется. Снижение не считается успехом само по себе.</div></div></div>${valentin(quotes['day'+day])}<div class="actions">${btn(day===7?'Перейти к решению':'Открыть следующий день',next,'black')}</div>`)}
function bindSingle(key,value){state[key]=value;const map={decisionPreset:'decision',expectedPreset:'expectedOutcome',agreementWhoPreset:'agreementWho',agreementSaidPreset:'agreementSaid',recheckPreset:'recheckTrigger',x1:'agreementInference',x2:'agreementKnown',x3:'agreementCheck',x4:'trustReflection',x5:'uncomfortableFailure',x6:'rationalizedSignal',x7:'greenState',x8:'yellowState',x9:'redLine',x10:'redLine',x11:'proArguments',x12:'counterArguments',x13:'falsificationFact',x14:'errorCost',x15:'inactionCost',x16:'planB'};const target=map[key];if(target)state[target]=value==='__custom'?'':value;if(key==='control1Preset'){const found=evidenceOptions.find(x=>x[0]===value||x[1]===value);state.control1=found?found[1]:(value==='__custom'?'':value)}save();render()}
const screens={};
