Object.assign(screens,{
d6falsify(){shell(`<div class="eyebrow danger">День 6 / фальсификация</div><h2>Какой факт заставит вас признать, что вы ошибались?</h2>${editableSingle({key:'falsificationFact',presetKey:'x13',options:falsifyOptions,value:state.falsificationFact,label:'Факт, который меняет мнение'})}${valentin(quotes.day6)}${err('falsifyErr')}<div class="footer-nav">${back('d6counter')}<button class="btn" id="falsifyNext">Получить результат дня</button></div>`)},
d6summary(){summary(6,'d7intro')},
d7intro(){dayIntro(7,'Смелость без идиотизма','О — ответ','d7error')},
d7error(){shell(`<div class="eyebrow danger">День 7 / цена ошибки</div><h2>Что произойдёт, если вы сделаете и окажетесь неправы?</h2>${editableSingle({key:'errorCost',presetKey:'x14',options:errorOptions,value:state.errorCost,label:'Цена ошибки'})}${err('errorErr')}<div class="footer-nav">${back('d7intro')}<button class="btn" id="errorNext">Продолжить</button></div>`)},
d7inaction(){shell(`<div class="eyebrow">День 7 / цена бездействия</div><h2>А что произойдёт, если вы не сделаете?</h2>${editableSingle({key:'inactionCost',presetKey:'x15',options:inactionOptions,value:state.inactionCost,label:'Цена бездействия'})}${err('inactionErr')}<div class="footer-nav">${back('d7error')}<button class="btn" id="inactionNext">Продолжить</button></div>`)},
d7planb(){shell(`<div class="eyebrow">День 7 / Plan B</div><h2>Если реализуется плохая версия — что вы будете делать?</h2>${editableSingle({key:'planB',presetKey:'x16',options:planBOptions,value:state.planB,label:'Plan B'})}${valentin(quotes.day7)}${err('planErr')}<div class="footer-nav">${back('d7inaction')}<button class="btn" id="planNext">Получить итоговую динамику</button></div>`)},
d7decision(){const r=state.dayResults.day7;shell(`<div class="eyebrow">День 7 / финальное решение</div><div class="status-strip"><div><div class="eyebrow">Расчётная динамика</div><div class="delta">${r.from}% → ${r.to}%</div></div><div><p>${esc(r.explanation)}</p></div></div><h2>Вы всё ещё хотите это делать?</h2><div class="choice-grid"><button class="choice ${state.finalDecision==='do'?'selected':''}" data-final="do">Да. Делать.</button><button class="choice ${state.finalDecision==='change'?'selected':''}" data-final="change">Да, но изменить условия.</button><button class="choice ${state.finalDecision==='stop'?'selected':''}" data-final="stop">Нет.</button></div>${err('finalErr')}<div class="footer-nav">${back('d7planb')}<button class="btn" id="finalNext">Зафиксировать решение</button></div>`)},
verdict(){const copy={do:'После всех проверок идея всё ещё выглядит разумно. Придётся делать.',change:'Вы не отказались от решения. Вы перестали принимать его в первоначальной комплектации.',stop:'Отказ от плохой идеи тоже является решением. Хотя выглядит менее героически.'}[state.finalDecision];valentinShell(`<div class="eyebrow">Валентин / вердикт</div><h2>Система решение не принимала.</h2><div class="quote">Вы дошли до него самостоятельно. Это и была неприятная часть.</div><p class="quote" style="font-size:24px">${esc(copy)}</p><div class="actions"><button class="btn" data-go="examIntro">Перейти к экзамену</button></div>`)},
});
