window.DEMENTOR_SITE_CONFIG=Object.freeze({
  version:'2026-08-25',
  canonicalOrigin:'https://degradation-club.vercel.app',
  contacts:{
    enabled:false,
    endpoint:null,
    publicEmail:null,
    socialLinks:[]
  },
  donate:{
    enabled:false,
    provider:null,
    checkoutUrl:null,
    currency:null,
    recurring:false
  },
  merch:{
    catalogEnabled:true,
    checkoutEnabled:false,
    checkoutProvider:null,
    checkoutUrl:null
  },
  events:{
    registrationEnabled:false,
    registrationProvider:null,
    registrationUrl:null
  },
  community:{
    membershipEnabled:false,
    membershipProvider:null,
    membershipUrl:null
  },
  onboarding:{
    storageKey:'dementorClubOnboardingV3',
    storage:'localStorage'
  }
});
if(typeof document!=='undefined'){
  (()=>{if(!document.querySelector('script[src="/dementor-relations-v1.js"]')){const s=document.createElement('script');s.src='/dementor-relations-v1.js';s.defer=true;document.head.appendChild(s)}})();
}
