(()=>{
const root=document.getElementById('app'),$=q=>root.querySelector(q),$$=q=>[...root.querySelectorAll(q)];
let page='person',char='gena',connectFrom=null,scale=.72,pan={x:0,y:0},gesture=new Map(),drag=null,autoTimer=null;
const looks={gena:{head:'ушанка / очки',outfit:'рубашка / шорты',accessory:'сигара / борода',emotion:'нейтральная'},marta:{head:'соломенная шляпа',outfit:'цветочное платье',accessory:'без аксессуара',emotion:'скептическая'}};
const specs={criticism:{f:'TRIGGER',t:'КРИТИКА',sub:'событие',out:1},beright:{f:'IMPULSE',t:'БЫТЬ ПРАВЫМ',sub:'настоять',in:1,out:1,weight:5},understand:{f:'IMPULSE',t:'ПОНЯТЬ',sub:'разобраться',in:1,out:1,weight:4},beliked:{f:'IMPULSE',t:'НРАВИТЬСЯ',sub:'сохранить контакт',in:1,out:1,weight:3},explain:{f:'REACTION',t:'ОБЪЯСНИТЬ',sub:'аргументировать',in:1,out:1},pressure:{f:'REACTION',t:'ДАВИТЬ',sub:'на противоречие',in:1,out:1},agree:{f:'REACTION',t:'СОГЛАСИТЬСЯ',sub:'снять конфликт',in:1,out:1},joke:{f:'REACTION',t:'ПОШУТИТЬ',sub:'разрядить',in:1,out:1},repeat:{f:'CONTROL',t:'REPEAT',sub:'повторить',in:1,out:1,count:2},pause:{f:'ABILITY',t:'ПАУЗА',sub:'восстановиться',in:1,out:1},interrupt:{f:'ABILITY',t:'ПЕРЕХВАТ',sub:'сбить восстановление',in:1,out:1},stop:{f:'CONTROL',t:'STOP',sub:'конец',in:1}};
const presetDefs={henpecked:{label:'ПОДКАБЛУЧНИК',types:['criticism','beliked','agree','stop']},preacher:{label:'ПРОПОВЕДНИК',types:['criticism','beright','explain','repeat','stop']},diplomat:{label:'ХОЛОДНЫЙ ДИПЛОМАТ',types:['criticism','understand','pause','explain','stop']},chaos:{label:'АВАНТЮРИСТ',types:['criticism','beliked','joke','repeat','stop']},pro:{label:'DEMENTOR PRO',types:['criticism','understand','pressure','repeat','interrupt','stop']}};
let currentPreset='diplomat',nodes=[],edges=[],A,B,phrases=0,loops=0,goalA=0,goalB=0,lastReactionA='',lastExec=[];
const sem={agree:{s:{energy:-2,brain:-2,tension:-8,contact:5},o:{tension:-5,contact:3}},joke:{s:{energy:-3,brain:2,tension:-5,contact:4},o:{tension:-4,contact:3}},explain:{s:{energy:-3,brain:5,tension:3,contact:-1},o:{brain:4,tension:3,contact:-2}},pressure:{s:{energy:-4,brain:4,tension:4,contact:-2},o:{brain:13,tension:9,contact:-5}},pause:{s:{energy:4,brain:-18,tension:-12,contact:-1},o:{}},interrupt:{s:{energy:-2,brain:1,tension:2,contact:-1},o:{brain:6,tension:5,energy:-1}}};
function toast(s){let t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1400)}
function show(name){page=name;$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));const m={person:['ГЕНА / PERSON','Собери внешний образ'],brain:['ГЕНА / BRAIN','Собери характер'],talk:['ГЕНА × МАРТА / TALK','Проверь модель в разговоре']}[name];$('#title').textContent=m[0];$('#sub').textContent=m[1];if(name==='brain')renderGraph();if(name==='talk')renderTalk()}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.nav)));$('#back').onclick=()=>show(page==='talk'?'brain':page==='brain'?'person':'person');
function openSheet(title,body){$('#sheetTitle').textContent=title;$('#sheetBody').innerHTML=body;$('#sheetback').classList.add('show')}function closeSheet(){$('#sheetback').classList.remove('show')}$('#sheetback').addEventListener('click',e=>{if(e.target===$('#sheetback'))closeSheet()});
function syncPerson(){let s=looks[char];$('#personImg').src=char==='gena'?'assets/gena-full.svg':'assets/marta-full.svg';$('#personName').textContent=char==='gena'?'ГЕНА':'МАРТА';$('#lookLine').textContent=[s.head,s.outfit,s.accessory].join(' · ');$('#headLabel').textContent=s.head;$('#outfitLabel').textContent=s.outfit;$('#accessoryLabel').textContent=s.accessory;$('#emotionLabel').textContent=s.emotion;$$('[data-char]').forEach(b=>b.classList.toggle('active',b.dataset.char===char))}
$$('[data-char]').forEach(b=>b.onclick=()=>{char=b.dataset.char;syncPerson()});
const lookData={head:{title:'ГОЛОВА',img:'assets/accessories.svg',opts:['ушанка / очки','соломенная шляпа','бандана','цилиндр','без шляпы']},outfit:{title:'ОДЕЖДА',optsG:['рубашка / шорты','костюм','майка / шорты','пальто'],optsM:['цветочное платье','костюм','короткая юбка','майка / юбка']},accessory:{title:'АКСЕССУАРЫ',img:'assets/accessories.svg',opts:['сигара / борода','солнечные очки','наушники','без аксессуара']},emotion:{title:'ЭМОЦИЯ',img:'assets/emotions.svg',opts:['нейтральная','скептическая','злая','сонная','перегрев','довольная']}};
$$('[data-look]').forEach(b=>b.onclick=()=>{let k=b.dataset.look,d=lookData[k],img=d.img||(char==='gena'?'assets/male-outfits.svg':'assets/female-outfits.svg'),opts=d.opts||(char==='gena'?d.optsG:d.optsM);openSheet(d.title,`<div class="preview"><img src="${img}"></div><div class="sheetgrid">${opts.map(o=>`<button data-opt="${o}" class="${looks[char][k]===o?'selected':''}">${o}</button>`).join('')}</div>`);$('#sheetBody').querySelectorAll('[data-opt]').forEach(x=>x.onclick=()=>{looks[char][k]=x.dataset.opt;syncPerson();closeSheet();toast('ОБРАЗ ОБНОВЛЁН')})});
function loadPreset(k){currentPreset=k;let types=presetDefs[k].types;nodes=types.map((type,i)=>({id:'n'+i,type,x:90+i*215,y:180,p:{...(specs[type].weight?{weight:specs[type].weight}:{}),...(specs[type].count?{count:specs[type].count}:{})}}));edges=nodes.slice(0,-1).map((n,i)=>({from:n.id,to:nodes[i+1].id}));$('#presetName').textContent=presetDefs[k].label;resetTalk();renderGraph()}
function node(id){return nodes.find(n=>n.id===id)}function addEdge(a,b){if(a!==b&&!edges.some(e=>e.from===a&&e.to===b))edges.push({from:a,to:b})}
function renderGraph(){let svg=$('#graph');svg.innerHTML='';$('#graphState').textContent=nodes.some(n=>n.type==='criticism')&&nodes.some(n=>['explain','pressure','agree','joke'].includes(n.type))?'RUNNABLE':'INCOMPLETE';$('#connectNote').classList.toggle('show',!!connectFrom);let world=document.createElementNS('http://www.w3.org/2000/svg','g');world.setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${scale})`);svg.appendChild(world);edges.forEach(e=>{let a=node(e.from),b=node(e.to);if(!a||!b)return;let x1=a.x+190,y1=a.y+36,x2=b.x,y2=b.y+36,m=(x1+x2)/2,p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',`M${x1},${y1} C${m},${y1} ${m},${y2} ${x2},${y2}`);p.setAttribute('fill','none');p.setAttribute('stroke','#111');p.setAttribute('stroke-width','10');world.appendChild(p)});nodes.forEach(n=>{let sp=specs[n.type],g=document.createElementNS('http://www.w3.org/2000/svg','g');g.dataset.node=n.id;g.setAttribute('transform',`translate(${n.x} ${n.y})`);g.innerHTML=`<rect width="190" height="72" rx="4" fill="#111"/><rect width="54" height="72" fill="#dfff00"/><text x="65" y="20" fill="#aaa" font-size="10" font-family="monospace" font-weight="900">${sp.f}</text><text x="65" y="44" fill="#fff" font-size="15" font-family="monospace" font-weight="900">${sp.t}</text><text x="27" y="43" fill="#111" text-anchor="middle" font-size="15" font-family="monospace" font-weight="900">${n.p.weight?'×'+n.p.weight:n.p.count?'×'+n.p.count:'•'}</text>${sp.in?`<circle data-in="${n.id}" cx="0" cy="36" r="18" fill="#fff" stroke="#111" stroke-width="6"/>`:''}${sp.out?`<circle data-out="${n.id}" cx="190" cy="36" r="20" fill="#dfff00" stroke="#111" stroke-width="6"/>`:''}`;world.appendChild(g)})}
$('#connectNote').onclick=()=>{connectFrom=null;renderGraph()};
$('#add').onclick=()=>openSheet('ДОБАВИТЬ БЛОК',`<div class="sheetgrid">${Object.entries(specs).map(([k,v])=>`<button data-type="${k}"><b>${v.t}</b><br><small>${v.f}</small></button>`).join('')}</div>`);
$('#sheetBody').addEventListener('click',e=>{let b=e.target.closest('[data-type]');if(!b)return;let t=b.dataset.type,sp=specs[t];nodes.push({id:'n'+Date.now(),type:t,x:600-pan.x/scale,y:430-pan.y/scale,p:{...(sp.weight?{weight:sp.weight}:{}),...(sp.count?{count:sp.count}:{})}});closeSheet();renderGraph();toast('БЛОК ДОБАВЛЕН')});
$('#center').onclick=()=>{scale=.72;pan={x:0,y:0};renderGraph()};$('#layout').onclick=()=>{nodes.forEach((n,i)=>{n.x=80+(i%5)*220;n.y=130+Math.floor(i/5)*125});renderGraph()};
$('#presets').onclick=()=>openSheet('ПРЕСЕТЫ',`<div class="sheetgrid">${Object.entries(presetDefs).map(([k,p])=>`<button data-preset="${k}">${p.label}</button>`).join('')}</div>`);
$('#sheetBody').addEventListener('click',e=>{let b=e.target.closest('[data-preset]');if(!b)return;loadPreset(b.dataset.preset);closeSheet();toast('ПРЕСЕТ ЗАГРУЖЕН')});
const svg=$('#graph');svg.addEventListener('pointerdown',e=>{gesture.set(e.pointerId,{x:e.clientX,y:e.clientY});svg.setPointerCapture?.(e.pointerId);let out=e.target.closest('[data-out]'),inn=e.target.closest('[data-in]'),g=e.target.closest('[data-node]');if(out){connectFrom=out.dataset.out;renderGraph();return}if(inn&&connectFrom){addEdge(connectFrom,inn.dataset.in);connectFrom=null;renderGraph();toast('СВЯЗЬ ДОБАВЛЕНА');return}if(g){let n=node(g.dataset.node);drag={kind:'node',id:n.id,x:e.clientX,y:e.clientY,ox:n.x,oy:n.y};return}drag={kind:'pan',x:e.clientX,y:e.clientY,ox:pan.x,oy:pan.y}});
svg.addEventListener('pointermove',e=>{if(!gesture.has(e.pointerId))return;gesture.set(e.pointerId,{x:e.clientX,y:e.clientY});if(gesture.size===2){let pts=[...gesture.values()],d=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);if(!svg._pd)svg._pd=d;else{scale=Math.max(.38,Math.min(1.45,scale*d/svg._pd));svg._pd=d;renderGraph()}return}if(!drag)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(drag.kind==='node'){let n=node(drag.id);n.x=drag.ox+dx/scale;n.y=drag.oy+dy/scale}else{pan.x=drag.ox+dx;pan.y=drag.oy+dy}renderGraph()});svg.addEventListener('pointerup',e=>{gesture.delete(e.pointerId);if(gesture.size<2)svg._pd=null;drag=null});svg.addEventListener('pointercancel',e=>{gesture.delete(e.pointerId);drag=null});
function clamp(o){for(let k of ['energy','brain','tension','contact'])o[k]=Math.max(0,Math.min(100,o[k]))}function delta(o,d){for(let [k,v] of Object.entries(d||{}))o[k]=(o[k]||0)+v;clamp(o)}
function activeReaction(){let path=[],id=nodes.find(n=>n.type==='criticism')?.id,guard=0;while(id&&guard++<20){let n=node(id);if(!n)break;path.push(n);let e=edges.find(x=>x.from===id);id=e?.to}let r=path.find(n=>['explain','pressure','agree','joke'].includes(n.type))||{type:'explain',p:{}},repeat=path.find(n=>n.type==='repeat'),pause=path.some(n=>n.type==='pause'),interrupt=path.some(n=>n.type==='interrupt'),imp=path.find(n=>['understand','beright','beliked'].includes(n.type));return {r:r.type,repeat:repeat?.p.count||1,pause,interrupt,imp:imp?.type,path}}
function exec(actor){let self=actor==='A'?A:B,opp=actor==='A'?B:A,x=actor==='A'?activeReaction():{r:'explain',repeat:2,pause:self.brain>66,interrupt:false,imp:'beright',path:[]},s=sem[x.r]||sem.explain;if(x.pause)delta(self,sem.pause.s);delta(self,s.s);delta(opp,s.o);if(x.repeat>1){for(let i=1;i<x.repeat;i++){delta(self,Object.fromEntries(Object.entries(s.s).map(([k,v])=>[k,v*.5])));delta(opp,Object.fromEntries(Object.entries(s.o).map(([k,v])=>[k,v*.45])));self.brain+=1.5;loops++}}if(x.interrupt){delta(self,sem.interrupt.s);delta(opp,sem.interrupt.o)}clamp(self);clamp(opp);let gain=x.r==='pressure'?14:x.r==='explain'?9:x.r==='joke'?4:2;if(x.imp==='understand')gain+=4;if(x.imp==='beright')gain+=2;if(actor==='A')goalA=Math.min(100,goalA+gain);else goalB=Math.min(100,goalB+gain);lastExec=x.path;let line=x.r==='pressure'?'Ты держишь две несовместимые позиции. Какая из них настоящая?':x.r==='agree'?'Возможно. Давай не будем продавливать это сейчас.':x.r==='joke'?'Хорошо, считаем это контролируемой катастрофой.':'Давай разберём, где именно ломается аргумент.';log(actor,line)}
function log(actor,text){let d=document.createElement('div');d.className='msg '+(actor==='A'?'a':actor==='B'?'b':'sys');d.textContent=(actor==='A'?'ГЕНА: ':actor==='B'?'МАРТА: ':'')+text;$('#dialog').appendChild(d);$('#dialog').scrollTop=$('#dialog').scrollHeight}
function resetTalk(){A={energy:85,brain:15,tension:10,contact:60};B={energy:85,brain:15,tension:10,contact:60};phrases=loops=goalA=goalB=0;$('#dialog').innerHTML='';log('S','OBJECTIVE: ПЕРЕУБЕДИТЬ. Граф против графа.');renderTalk()}
function renderStats(el,o){el.innerHTML=[['ENERGY',o.energy],['BRAIN',o.brain],['TENSION',o.tension],['CONTACT',o.contact]].map(([k,v])=>`<div class="meterrow"><span>${k}</span><div class="meter"><i style="width:${v}%"></i></div><b>${Math.round(v)}</b></div>`).join('')}
function renderTalk(){renderStats($('#statsA'),A);renderStats($('#statsB'),B);$('#goalText').textContent=`${Math.round(goalA)}% / ${Math.round(goalB)}%`;$('#goalBar').style.width=Math.max(goalA,goalB)+'%'}
function step(){if(A.brain>=100||B.brain>=100||goalA>=100||goalB>=100){toast('МАТЧ ЗАВЕРШЁН');stopAuto();return}exec(phrases%2===0?'A':'B');phrases++;renderTalk()}
$('#next').onclick=step;function stopAuto(){clearInterval(autoTimer);autoTimer=null;$('#auto').textContent='AUTO'}$('#auto').onclick=()=>{if(autoTimer)stopAuto();else{autoTimer=setInterval(step,700);$('#auto').textContent='STOP'}};$('#testTalk').onclick=()=>{show('talk');toast('ЭКСПЕРИМЕНТ ЗАПУЩЕН')};
$('#patch').onclick=()=>{let r=nodes.find(n=>n.type==='repeat'),path=lastExec.length?lastExec:nodes.slice(0,5);openSheet('⚡ HOT PATCH',`<div class="cap">АКТИВНЫЙ ПУТЬ</div><p style="font:900 9px monospace">${path.map(n=>specs[n.type]?.t||n.type).join(' → ')}</p><div class="sheetgrid"><button id="reduce">REPEAT −1</button><button id="addPause">＋ PAUSE</button><button id="fullBrain">ОТКРЫТЬ BRAIN</button><button class="primary" id="apply">APPLY & CONTINUE</button></div>`);$('#reduce').onclick=()=>{if(r&&r.p.count>1){r.p.count--;renderGraph();toast('REPEAT УМЕНЬШЕН')}};$('#addPause').onclick=()=>{let target=r||nodes.find(n=>['explain','pressure'].includes(n.type));if(!target)return;let incoming=edges.find(e=>e.to===target.id);let p={id:'n'+Date.now(),type:'pause',x:target.x-180,y:target.y+110,p:{}};nodes.push(p);if(incoming){let from=incoming.from;incoming.to=p.id;edges.push({from:p.id,to:target.id})}renderGraph();toast('PAUSE ВСТАВЛЕН')};$('#fullBrain').onclick=()=>{closeSheet();show('brain')};$('#apply').onclick=()=>{closeSheet();show('talk');toast('PATCH ПРИМЕНЁН')}};
$('#menu').onclick=()=>{openSheet('МЕНЮ',`<div class="sheetgrid"><button data-goal="convince">ПЕРЕУБЕДИТЬ</button><button id="reset">RESET TALK</button><button id="brainJump">BRAIN</button><button id="personJump">PERSON</button></div>`);setTimeout(()=>{$('#reset').onclick=()=>{resetTalk();closeSheet()};$('#brainJump').onclick=()=>{closeSheet();show('brain')};$('#personJump').onclick=()=>{closeSheet();show('person')}},0)};
addEventListener('resize',()=>$('#qa').textContent='v1.2 · '+innerWidth);syncPerson();loadPreset('diplomat');resetTalk();renderGraph();
})();