import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.4/+esm';

const host=document.getElementById('applyHost');const cfg=window.DEMENTOR_SITE_CONFIG?.supabase;
const SPHERES=[['personality','Личность'],['work','Работа'],['consumption','Потребление'],['relationships','Отношения'],['control','Контроль'],['information','Информация'],['self_development','Саморазвитие'],['meaning','Смысл'],['technology','Технологии']];
const base=location.pathname.startsWith('/degradation_club/')?'/degradation_club':'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>{try{return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(v))}catch{return String(v||'—')}};

if(!host||!cfg?.enabled){if(host)host.innerHTML='<div class="dc-apply-error">Сервис заявок сейчас недоступен.</div>';}
else{
  const client=window.DEMENTOR_SUPABASE_CLIENT||createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,flowType:'pkce'}});window.DEMENTOR_SUPABASE_CLIENT=client;
  const {data:{session}}=await client.auth.getSession();const user=session?.user||null;
  const callback=location.origin+base+'/auth/callback/?next='+encodeURIComponent(base+'/join/apply/');
  async function login(){const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:callback}});if(error)showError(error.message)}
  function showError(msg){let el=host.querySelector('.dc-apply-error');if(!el){el=document.createElement('div');el.className='dc-apply-error';host.prepend(el)}el.textContent=msg}
  if(!user){host.innerHTML='<section class="dc-apply-gate"><div class="dc-apply-kicker">AUTHENTICATION ≠ MEMBERSHIP</div><h2>СНАЧАЛА<br>ПРЕДСТАВЬТЕСЬ.</h2><p>Заявка в клуб принадлежит конкретному человеку. Войдите через Google, затем заполните анкету. Сам вход не делает вас членом клуба.</p><button type="button" data-login>ВОЙТИ ЧЕРЕЗ GOOGLE</button></section>';host.querySelector('[data-login]').onclick=login;}
  else{
    const uid=user.id;
    const [{data:profile},{data:membership},{data:applications,error:appError}]=await Promise.all([
      client.from('profiles').select('id,email,full_name').eq('id',uid).maybeSingle(),
      client.from('dc_system_memberships').select('status,valid_from,valid_to').eq('profile_id',uid).maybeSingle(),
      client.from('join_applications').select('id,status,created_at,reviewed_at,answers').eq('profile_id',uid).order('created_at',{ascending:false}).limit(3)
    ]);if(appError)showError(appError.message);
    const member=membership?.status==='active';const current=applications?.[0]||null;
    if(member){host.innerHTML='<section class="dc-apply-done"><div class="dc-apply-kicker">MEMBERSHIP / ACTIVE</div><h2>ВЫ УЖЕ<br>В КЛУБЕ.</h2><p>Повторная заявка не требуется. Членство и рабочие роли продолжают жить отдельно от аккаунта.</p><p><a class="dc-apply-submit" href="'+base+'/workspace/">ОТКРЫТЬ ЛИЧНЫЙ КАБИНЕТ →</a></p></section>';}
    else if(current&&['submitted','reviewing','approved'].includes(current.status)){
      const interests=current.answers?.interest_distribution||{};host.innerHTML=`<section class="dc-apply-done"><div class="dc-apply-kicker">APPLICATION / ${esc(current.status).toUpperCase()}</div><h2>ЗАЯВКА<br>ПРИНЯТА.</h2><p>Отправлена ${date(current.created_at)}. Регистрация остаётся регистрацией, пока членство не подтверждено отдельно.</p><div class="dc-apply-section"><div class="dc-apply-kicker">РАСПРЕДЕЛЕНИЕ РЕГРЕССА</div>${SPHERES.map(([id,title])=>`<div class="dc-apply-status"><strong>${title}</strong><span>${Number(interests[id]||0)}%</span></div>`).join('')}</div><p><a class="dc-apply-submit" href="${base}/workspace/">В ЛИЧНЫЙ КАБИНЕТ →</a></p></section>`;
    }else renderForm(profile);

    function renderForm(profile){
      const parts=String(profile?.full_name||user.user_metadata?.full_name||user.user_metadata?.name||'').trim().split(/\s+/).filter(Boolean);const first=parts.shift()||'',last=parts.join(' ');
      host.innerHTML=`<form class="dc-apply-form" id="membershipForm"><section class="dc-apply-section"><div class="dc-apply-section-head"><div class="dc-apply-kicker">01 / PERSON</div><div><h2>КТО ВЫ?</h2><p>Минимум данных, чтобы заявка принадлежала человеку, а не электронной почте.</p></div></div><div class="dc-apply-grid"><div class="dc-field"><label for="firstName">Имя</label><input id="firstName" name="first_name" required autocomplete="given-name" value="${esc(first)}"></div><div class="dc-field"><label for="lastName">Фамилия</label><input id="lastName" name="last_name" required autocomplete="family-name" value="${esc(last)}"></div><div class="dc-field is-wide"><label for="socialUrl">Ссылка на социальную сеть / сайт</label><input id="socialUrl" name="social_url" required placeholder="https://…"></div><div class="dc-field is-wide"><label for="about">Кто вы — коротко</label><textarea id="about" name="about" required placeholder="Чем занимаетесь, что делаете, что считаете важным"></textarea></div><div class="dc-field is-wide"><label for="whyClub">Почему вы здесь</label><textarea id="whyClub" name="why_club" placeholder="Можно коротко. Можно не убеждать комиссию в своей нормальности."></textarea></div></div></section><section class="dc-apply-section"><div class="dc-apply-section-head"><div class="dc-apply-kicker">02 / INTEREST MAP</div><div><div class="dc-regress-title">РЕГРЕСС ОГРАНИЧЕН.<br>РАСПРЕДЕЛИТЕ БЕЗОТВЕТСТВЕННО.</div><p>У вас ровно 100%. Если увеличить одну область, остальные физически ужмутся. Это не результат DC-9, а карта того, куда вам интересно двигаться.</p></div></div><div class="dc-budget"><div><span>РАСПРЕДЕЛЕНО</span><strong id="budgetTotal">100 / 100</strong></div><div class="dc-regress-sub">ОДИН БЮДЖЕТ · ДЕВЯТЬ НАПРАВЛЕНИЙ</div></div><div class="dc-interest-list" id="interestList"></div></section><section class="dc-apply-foot"><p>Отправка создаёт JOIN APPLICATION. Она не создаёт membership автоматически и не делает человека Dementor.</p><button class="dc-apply-submit" type="submit">ПОДАТЬ ЗАЯВКУ →</button></section></form>`;
      const list=host.querySelector('#interestList');let values=[12,11,11,11,11,11,11,11,11];
      const distribute=(total,weights)=>{if(total<=0)return weights.map(()=>0);const sum=weights.reduce((a,b)=>a+b,0);const raw=(sum>0?weights:weights.map(()=>1)).map(w=>(sum>0?w/sum:1/weights.length)*total);const out=raw.map(Math.floor);let rest=total-out.reduce((a,b)=>a+b,0);const order=raw.map((v,i)=>({i,f:v-Math.floor(v)})).sort((a,b)=>b.f-a.f);for(let k=0;k<rest;k++)out[order[k%order.length].i]++;return out};
      const setValue=(idx,target)=>{target=Math.max(0,Math.min(100,Math.round(Number(target)||0)));const others=values.filter((_,i)=>i!==idx);const distributed=distribute(100-target,others);const next=[];let j=0;for(let i=0;i<values.length;i++)next[i]=i===idx?target:distributed[j++];values=next;paint()};
      const paint=()=>{[...list.querySelectorAll('[data-interest]')].forEach((row,i)=>{const input=row.querySelector('input'),out=row.querySelector('output');input.value=values[i];input.style.setProperty('--p',values[i]+'%');out.value=values[i]+'%';out.textContent=values[i]+'%'});host.querySelector('#budgetTotal').textContent=values.reduce((a,b)=>a+b,0)+' / 100'};
      list.innerHTML=SPHERES.map(([id,title],i)=>`<label class="dc-interest-row" data-interest="${id}"><span class="dc-interest-name">${title}</span><input type="range" min="0" max="100" step="1" value="${values[i]}" aria-label="Интерес: ${title}"><output class="dc-interest-value">${values[i]}%</output></label>`).join('');[...list.querySelectorAll('input')].forEach((input,i)=>input.addEventListener('input',()=>setValue(i,input.value)));paint();
      host.querySelector('#membershipForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button[type=submit]');const fd=new FormData(form);const firstName=String(fd.get('first_name')||'').trim(),lastName=String(fd.get('last_name')||'').trim(),social=String(fd.get('social_url')||'').trim(),about=String(fd.get('about')||'').trim(),why=String(fd.get('why_club')||'').trim();if(!firstName||!lastName||!social||!about){showError('Заполните имя, фамилию, ссылку и короткое описание.');return}const interest_distribution=Object.fromEntries(SPHERES.map(([id],i)=>[id,values[i]]));if(Object.values(interest_distribution).reduce((a,b)=>a+b,0)!==100){showError('Распределение должно оставаться ровно 100%.');return}button.disabled=true;button.textContent='ОТПРАВЛЯЕМ…';const fullName=`${firstName} ${lastName}`.trim();const answers={version:'dc-membership-application-v1',first_name:firstName,last_name:lastName,social_url:social,about,why_club:why||null,interest_distribution,interest_total:100};const {error}=await client.from('join_applications').insert({profile_id:uid,email:user.email||profile?.email||'',full_name:fullName,answers,status:'submitted',source:'dc-membership-application-v1'});if(!error){await client.from('profiles').update({full_name:fullName,updated_at:new Date().toISOString()}).eq('id',uid);location.reload();return}button.disabled=false;button.textContent='ПОДАТЬ ЗАЯВКУ →';showError(error.code==='23505'?'Активная заявка уже существует. Обновите страницу.':error.message)})
    }
  }
}
