import {getClient,currentSession,loginWithGoogle,getEntryStatus,signedMediaUrl,esc,formatDate,errorMessage,route} from '/community-runtime-v1.js';

const host=document.getElementById('artifactHost');const stateEl=document.getElementById('artifactState');let client=null,session=null,artifact=null,reactions=[],responses=[];
function idFromLocation(){const query=new URLSearchParams(location.search).get('id');if(query)return query;const parts=location.pathname.split('/').filter(Boolean);const i=parts.indexOf('artifact');return i>=0&&parts[i+1]&&parts[i+1]!=='index.html'?parts[i+1]:null}
function fail(error){stateEl.textContent='ERROR';host.innerHTML=`<div class="dc-artifact-error">${esc(errorMessage(error))}</div>`}
function avatar(profile){if(profile?.avatar_url)return `<img class="dc-artifact-avatar" src="${esc(profile.avatar_url)}" alt="">`;return `<span class="dc-artifact-avatar empty">${esc(String(profile?.display_name||'?').charAt(0).toUpperCase())}</span>`}

async function load(){
  const id=idFromLocation();if(!id)throw new Error('ARTIFACT_ID_REQUIRED');
  const result=await client.from('dc_artifacts').select('id,author_profile_id,title,body,external_url,status,visibility,starts_at,expires_at,published_at,created_at,closed_at').eq('id',id).maybeSingle();if(result.error)throw result.error;if(!result.data)throw new Error('ARTIFACT_NOT_FOUND');artifact=result.data;
  const [profileResult,reactionResult,mediaResult,responseResult]=await Promise.all([
    client.from('dc_member_public_profiles').select('profile_id,display_name,nickname,avatar_url,member_since').eq('profile_id',artifact.author_profile_id).maybeSingle(),
    client.from('dc_artifact_reactions').select('id,profile_id,reaction_type').eq('artifact_id',artifact.id),
    client.from('dc_artifact_media').select('id,media_type,storage_path,metadata').eq('artifact_id',artifact.id),
    client.from('dc_artifact_responses').select('id,responder_profile_id,message,status,created_at').eq('artifact_id',artifact.id)
  ]);for(const r of [profileResult,reactionResult,mediaResult,responseResult])if(r.error)throw r.error;
  reactions=reactionResult.data||[];responses=responseResult.data||[];const profile=profileResult.data||null;const media=mediaResult.data||[];const signed=[];for(const item of media){let url=null;try{url=await signedMediaUrl(client,item.storage_path)}catch{}signed.push({...item,url})}render(profile,signed);
}

function render(profile,media){
  const mine=artifact.author_profile_id===session.user.id;const myReaction=reactions.some(r=>r.profile_id===session.user.id);const myResponse=responses.find(r=>r.responder_profile_id===session.user.id&&r.status==='submitted');const incoming=mine?responses.filter(r=>r.status==='submitted').length:0;const item=media[0];let mediaHtml='';if(item?.url)mediaHtml=item.media_type==='image'?`<div class="dc-artifact-media"><img src="${esc(item.url)}" alt="Прикреплённое изображение"></div>`:`<div class="dc-artifact-media"><a class="dc-artifact-file" href="${esc(item.url)}" target="_blank" rel="noopener">ФАЙЛ / ${esc(item.metadata?.name||'ОТКРЫТЬ')} ↗</a></div>`;
  stateEl.textContent=`ARTIFACT / ${artifact.status.toUpperCase()}`;
  host.innerHTML=`<article class="dc-artifact-record"><div class="dc-artifact-meta"><span>ID / ${esc(artifact.id.slice(0,8).toUpperCase())}</span><span>STATUS / ${esc(artifact.status.toUpperCase())}</span><span>${artifact.expires_at?`EXPIRES / ${formatDate(artifact.expires_at)}`:'PERSISTENT'}</span></div><div class="dc-artifact-author">${avatar(profile)}<div><strong>${esc(profile?.display_name||'MEMBER')}</strong>${profile?.nickname?`<span>@${esc(profile.nickname.replace(/^@/,''))}</span>`:''}</div></div>${artifact.title?`<h1>${esc(artifact.title)}</h1>`:'<h1>ARTIFACT.</h1>'}<div class="dc-artifact-body">${esc(artifact.body)}</div>${mediaHtml}${artifact.external_url?`<p><a class="dc-artifact-link" href="${esc(artifact.external_url)}" target="_blank" rel="noopener">ВНЕШНЯЯ ССЫЛКА ↗</a></p>`:''}<div class="dc-artifact-actions"><span class="dc-artifact-action" aria-disabled="true">ИНТЕРЕСНО / ${reactions.length}</span><button class="dc-artifact-action${myReaction?' primary':''}" type="button" id="detailReaction">${myReaction?'✓ ИНТЕРЕСНО':'МНЕ ЭТО НАДО'}</button>${mine?`<span class="dc-artifact-action" aria-disabled="true">ОТКЛИКОВ / ${incoming}</span>${artifact.status==='active'?'<button class="dc-artifact-action" type="button" id="detailClose">УБРАТЬ С ДОСКИ</button>':''}`:`<button class="dc-artifact-action${myResponse?' primary':''}" type="button" id="detailResponse" ${myResponse?'disabled':''}>${myResponse?'ОТКЛИК ОТПРАВЛЕН':'ОТКЛИКНУТЬСЯ'}</button>`}<a class="dc-artifact-action" href="${route('/workspace/board/')}">← BOARD</a></div><div id="responseHost"></div></article>`;
  document.getElementById('detailReaction').onclick=toggleReaction;document.getElementById('detailClose')?.addEventListener('click',closeArtifact);document.getElementById('detailResponse')?.addEventListener('click',openResponse);
}

async function toggleReaction(event){const button=event.currentTarget;button.disabled=true;const active=reactions.some(r=>r.profile_id===session.user.id);try{if(active){const result=await client.from('dc_artifact_reactions').delete().eq('artifact_id',artifact.id).eq('profile_id',session.user.id).eq('reaction_type','interested');if(result.error)throw result.error}else{const result=await client.from('dc_artifact_reactions').insert({artifact_id:artifact.id,profile_id:session.user.id,reaction_type:'interested'});if(result.error)throw result.error}await load()}catch(error){button.disabled=false;fail(error)}}
function openResponse(){const responseHost=document.getElementById('responseHost');responseHost.innerHTML='<div class="dc-artifact-response"><textarea maxlength="2000" placeholder="Можно коротко написать автору, зачем вы откликаетесь."></textarea><div class="dc-artifact-actions"><button class="dc-artifact-action primary" type="button" id="sendResponse">ОТПРАВИТЬ</button><button class="dc-artifact-action" type="button" id="cancelResponse">ОТМЕНА</button></div></div>';document.getElementById('cancelResponse').onclick=()=>{responseHost.innerHTML=''};document.getElementById('sendResponse').onclick=sendResponse}
async function sendResponse(event){const button=event.currentTarget;const text=host.querySelector('.dc-artifact-response textarea')?.value.trim()||null;button.disabled=true;button.textContent='ОТПРАВЛЯЕМ…';const result=await client.from('dc_artifact_responses').insert({artifact_id:artifact.id,responder_profile_id:session.user.id,message:text,status:'submitted'});if(result.error){button.disabled=false;button.textContent='ОТПРАВИТЬ';fail(result.error);return}await load()}
async function closeArtifact(){if(!confirm('Убрать Artifact с активной доски и перенести в архив?'))return;const result=await client.rpc('dc_close_artifact_v1',{p_artifact_id:artifact.id});if(result.error){fail(result.error);return}location.assign(route('/workspace/board/'))}

async function boot(){client=getClient();session=await currentSession(client);if(!session){stateEl.textContent='AUTH REQUIRED';host.innerHTML='<div class="dc-artifact-service"><button class="dc-artifact-action primary" id="artifactLogin" type="button">ВОЙТИ ЧЕРЕЗ GOOGLE →</button></div>';document.getElementById('artifactLogin').onclick=()=>loginWithGoogle(location.pathname+location.search,client).catch(fail);return}const status=await getEntryStatus(client);if(!status.membership_active){stateEl.textContent='MEMBERSHIP REQUIRED';host.innerHTML=`<div class="dc-artifact-service">ARTIFACT ДОСТУПЕН ТОЛЬКО УЧАСТНИКАМ. <a href="${route('/join/')}">ПРОЙТИ GATE →</a></div>`;return}await load()}
boot().catch(fail);
