Object.assign(screens,{
d6falsify(){shell(`<div class="eyebrow danger">День 6 / фальсификация</div><h2>Какой факт заставит вас признать, что вы ошибались?</h2>${editableSingle({key:'falsificationFact',presetKey:'x13',options:falsifyOptions,value:state.falsificationFact,label:'Факт, который меняет мнение'})}${valentin(quotes.day6)}${err('falsifyErr')}<div class="footer-nav">${back('d6counter')}<button class="btn" id="falsifyNext">Получить результат дня</button></div>`)},
d6summary(){summary(6,'d7intro')},
d7intro(){dayIntro(7,'Смелость без идиотизма','О — ответ','d7error')},
d7error(){shell(`<div class="eyebrow danger">День 7 / цена ошибки</div><h2>Что произойдёт, если вы сделаете и окажетесь неправы?</h2>${editableSingle({key:'errorCost',presetKey:'x14',options:errorOptions,value:state.errorCost,label:'Цена ошибки'})}${err('errorErr')}<div class="footer-nav">${back('d7intro')}<button class="btn" id="errorNext">Продолжить</button></div>`)},
d7inaction(){shell(`<div class="eyebrow">День 7 / цена бездействия</div><h2>А что произойдёт, если вы не сделаете?</h2>${editableSingle({key:'inactionCost',presetKey:'x15',options:inactionOptions,value:state.inactionCost,label:'Цена бездействия'})}${err('inactionErr')}<div class="footer-nav">${back('d7error')}<button class="btn" id="inactionNext">Продолжить</button></div>`)},
d7planb(){shell(`<div class="eyebrow">День 7 / Plan B</div><h2>Если реализуется плохая версия — что вы будете делать?</h2>${editableSingle({key:'planB',presetKey:'x16',options:planBOptions,value:state.planB,label:'Plan B'})}${valentin(quotes.day7)}${err('planErr')}<div class="footer-nav">${back('d7inaction')}<button class="btn" id="planNext">Получить итоговую динамику</button></div>`)},
d7decision(){const r=state.dayResults.day7;shell(`<div class="eyebrow">День 7 / финальное решение</div><div class="status-strip"><div><div class="eyebrow">Расчётная динамика</div><div class="delta">${r.from}% → ${r.to}%</div></div><div><p>${esc(r.explanation)}</p></div></div><h2>Вы всё ещё хотите это делать?</h2><div class="choice-grid"><button class="choice ${state.finalDecision==='do'?'selected':''}" data-final="do">Да. Делать.</button><button class="choice ${state.finalDecision==='change'?'selected':''}" data-final="change">Да, но изменить условия.</button><button class="choice ${state.finalDecision==='stop'?'selected':''}" data-final="stop">Нет.</button></div>${err('finalErr')}<div class="footer-nav">${back('d7planb')}<button class="btn" id="finalNext">Зафиксировать решение</button></div>`)},
verdict(){const copy={do:'После всех проверок идея всё ещё выглядит разумно. Придётся делать.',change:'Вы не отказались от решения. Вы перестали принимать его в первоначальной комплектации.',stop:'Отказ от плохой идеи тоже является решением. Хотя выглядит менее героически.'}[state.finalDecision];valentinShell(`<div class="eyebrow">Валентин / вердикт</div><h2>Система решение не принимала.</h2><div class="quote">Вы дошли до него самостоятельно. Это и была неприятная часть.</div><p class="quote" style="font-size:24px">${esc(copy)}</p><div class="actions"><button class="btn" data-go="examIntro">Перейти к экзамену</button></div>`)},
examIntro(){shell(`<div class="eyebrow">Экзамен / новое дело</div><h2>Теперь без вашего контекста</h2><div class="case">Знакомый предлагает вложить €40 000 в новый проект. Похожий бизнес он уже запускал в другом городе. По его расчётам проект окупится за 18 месяцев. Уже есть ещё два инвестора. Помещение найдено. Решение нужно принять до пятницы.</div><p class="lead">Не выбирайте «да/нет». Найдите то, чего вы ещё не знаете.</p><div class="actions">${btn('Начать экзамен','examQuestions','black')}</div>`)},
examQuestions(){shell(`<div class="eyebrow danger">Экзамен / неизвестные</div><h2>Что нужно узнать перед ответом?</h2>${multiPicker({key:'examQuestions',options:['Кто и чем отвечает за результат?','На чём основана окупаемость 18 месяцев?','Какие юридические обязательства я принимаю?','Что произойдёт, если выручка будет ниже плана?','Как и когда можно выйти из проекта?','Какие факты уже подтверждены независимо?','Какие зависимости есть от помещения / партнёров?','Какой ранний сигнал покажет, что план ломается?'],min:5,placeholder:'Добавьте свой вопрос'})}${err('examErr')}<div class="footer-nav">${back('examIntro')}<button class="btn" id="examNext">Проверить</button></div>`)},
examResult(){shell(`<div class="eyebrow">Экзамен / результат</div><h2>${state.examPassed?'Решение не принято':'Неизвестных пока мало'}</h2><p class="lead">${state.examPassed?'Из-за недостатка данных. Вы отказались изображать уверенность там, где информации недостаточно.':'Вопросы есть, но покрыто слишком мало типов неизвестных.'}</p><div class="actions">${state.examPassed?btn('Завершить дело','completed','black'):btn('Вернуться к вопросам','examQuestions')}</div>`)},
completed(){state.status='completed';state.completedAt=state.completedAt||new Date().toISOString();save();shell(`<div class="eyebrow">Дело завершено</div><h2>Система решение не принимала.</h2><p class="lead">Она только заставила вас сделать работу перед решением.</p><div class="stats"><div class="stat"><span>Было</span><b>${state.initialConfidence}%</b></div><div class="stat"><span>Стало</span><b>${state.currentConfidence}%</b></div><div class="stat"><span>Финал</span><b style="font-size:20px">${state.finalDecision==='do'?'ДЕЛАТЬ':state.finalDecision==='change'?'ИЗМЕНИТЬ УСЛОВИЯ':'НЕ ДЕЛАТЬ'}</b></div></div><div class="actions">${btn('Открыть карту опасности','dangerMap')}</div>`)},
dangerMap(){const vals=Object.values(state.assumptionTypes),known=vals.filter(x=>x==='ЗНАЮ').length,ass=vals.filter(x=>x==='ПРЕДПОЛАГАЮ').length,said=vals.filter(x=>x==='МНЕ СКАЗАЛИ').length;shell(`<div class="eyebrow">Артефакт курса</div><h2>Карта опасности</h2><div class="danger-map"><h3>${esc(state.sessionId)}</h3><section><b>Решение</b><p>${esc(state.decision)}</p></section><section><b>Ожидаемый результат</b><p>${esc(state.expectedOutcome)}</p></section><section><b>Предпосылки</b><p>ЗНАЮ ${known} · ПРЕДПОЛАГАЮ ${ass} · МНЕ СКАЗАЛИ ${said}</p></section><section><b>Способы провала</b><p>${state.failureModes.map(esc).join(' · ')}</p></section><section><b>Сигналы</b><p>${state.signals.map(esc).join(' · ')}</p></section><section><b>Красная линия</b><p><span class="stamp">Красная линия</span><br>${esc(state.redLine)}</p></section><section><b>Цена ошибки</b><p>${esc(state.errorCost)}</p><b>Цена бездействия</b><p>${esc(state.inactionCost)}</p><b>Plan B</b><p>${esc(state.planB)}</p></section><section><b>Траектория</b><p>${state.confidenceHistory.map(x=>`${esc(x.stage)}: ${x.value}%`).join(' → ')}</p></section></div><div class="actions"><button class="btn alt" onclick="window.print()">Распечатать</button>${btn('Получить сертификат','certificate')}</div>`)},
certificate(){shell(`<div class="eyebrow">Финальный артефакт</div><h2>Сертификат</h2><div class="cert"><div class="eyebrow danger">Министерство профилактики здравого смысла</div><h3>Сертификат повышенной подозрительности</h3><p>Настоящим подтверждается, что участник перестал считать отсутствие плохих новостей хорошей новостью.</p><h3 style="margin-top:30px">Опасно думающий гражданин I класса</h3><p>Валентин Лосев</p></div><div class="actions"><button class="btn alt" onclick="window.print()">Распечатать</button>${btn('Посмотреть прототип письма','emailFinish')}</div>`)},
emailFinish(){shell(`<div class="eyebrow">Prototype / e-mail result</div><h2>Ваше дело завершено</h2><div class="email-preview"><div class="subject">Тема: ваше решение пережило проверку</div><p>Исходная уверенность: <b>${state.initialConfidence}%</b><br>Расчётная финальная: <b>${state.currentConfidence}%</b></p><p>Финальное решение: <b>${state.finalDecision==='do'?'ДЕЛАТЬ':state.finalDecision==='change'?'ИЗМЕНИТЬ УСЛОВИЯ':'НЕ ДЕЛАТЬ'}</b>.</p><p>В production здесь будет ссылка на сохранённую Карту опасности.</p><p>— Валентин</p></div><div class="note">Это локальная симуляция. Письмо не отправлено.</div>`)},
recovery(){shell(`<div class="eyebrow danger">Ошибка состояния</div><h2>Дело повреждено сильнее, чем планировалось</h2><div class="actions"><button class="btn danger" id="recoverReset">Начать заново</button></div>`) }
});
