const DATA={
  valentin:{name:'Валентин',slug:'valentin',role:'DEMENTOR',summary:'Самостоятельный онлайн-курс. Минимальный сценарий workspace без событий и participant-management.',programs:[{id:'danger',title:'Думай с опасностью',type:'course',delivery:'self_paced',status:'approved-draft',uiStatus:'ACTIVE',assignment:'PROGRAM_OWNER',description:'Курс последовательной деградации уверенности',runs:false,content:'7 модулей · Карта опасности · web/self-paced'}],events:[],projects:[]},
  nikita:{name:'Никита',slug:'nikita',role:'DEMENTOR',summary:'Автор цифрового адаптивного card-course. Основная рабочая поверхность — структура и карточки программы.',programs:[{id:'money',title:'Деньги на ветер',type:'course',delivery:'adaptive_digital',status:'MVP in development',uiStatus:'ACTIVE',assignment:'PROGRAM_AUTHOR',description:'Цифровой адаптивный карточечный курс',runs:false,content:'8+ карточек · branching · local adaptive MVP'}],events:[],projects:[]},
  evgeniy:{name:'Евгений',slug:'evgeniy',role:'DEMENTOR',summary:'Физический experience-program. Runs предусмотрены архитектурно, но пока не активны — набор не открыт.',programs:[{id:'courage',title:'Слабоумие и отвага',type:'experience',delivery:'physical',status:'planned',uiStatus:'PLANNED',assignment:'PROGRAM_OWNER',description:'Курс принятия решений в условиях отрицательного присутствия логики',runs:'planned',content:'Варшава / Гданьск · разговор → авиационный опыт → разговор'}],events:[],projects:[]},
  gabil:{name:'Габиль',slug:'gabil',role:'DEMENTOR',summary:'Самый насыщенный сценарий: recurring practice + отдельное planned-событие.',programs:[{id:'not-team',title:'НЕ КОМАНДА',type:'practice',delivery:'recurring',status:'active',uiStatus:'ACTIVE',assignment:'FACILITATOR',description:'Регулярная групповая практика',runs:true,content:'Каждый понедельник · 10:00 · Europe/Madrid'}],events:[{id:'fuengirola',title:'Фуэнхирола',type:'event',status:'planned',uiStatus:'PLANNED',assignment:'EVENT_HOST',description:'Лаборатория несовместимых очевидностей',meta:'Fuengirola, Spain · до 7 участников'}],projects:[]}
};

let state={person:'valentin',route:'home',entity:null,filter:'all'};
const view=document.getElementById('appView');
const topTitle=document.getElementById('topTitle');
const personSelect=document.getElementById('personSelect');
const personRole=document.getElementById('personRole');

const badge=(text,kind='')=>`<span class="dcw-badge ${kind?`dcw-badge--${kind}`:''}">${text}</span>`;
const statusBadge=(s)=>badge(s,s==='ACTIVE'?'active':s==='PLANNED'?'planned':'waiting');
const roleBadge=(r)=>badge(r,'role');
const source=()=>`<span class="dcw-source">SOURCE: DEMENTOR CLUB CANON · CONFIRMED/PLANNED AS MARKED</span>`;

function nav(route,entity=null){state.route=route;state.entity=entity;document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('is-active',b.dataset.route===route));render();}
function setPerson(p){state.person=p;state.route='home';state.entity=null;state.filter='all';personSelect.value=p;personRole.textContent=DATA[p].role;render();}

function render(){const p=DATA[state.person];topTitle.textContent=state.route==='home'?'HOME':state.route==='work'?'MY WORK':state.route==='profile'?'MY PROFILE':'ENTITY';
 if(state.route==='home')view.innerHTML=home(p); else if(state.route==='work')view.innerHTML=work(p); else if(state.route==='profile')view.innerHTML=profile(p); else if(state.route==='program')view.innerHTML=programPage(p,state.entity); else if(state.route==='event')view.innerHTML=eventPage(p,state.entity); else if(state.route==='run')view.innerHTML=runPage(p,state.entity); bindDynamic();}

function head(title,desc){return `<div class="dcw-page-head"><div><div class="dcw-kicker">DEMENTOR CLUB / ${DATA[state.person].name.toUpperCase()}</div><h1>${title}</h1></div><p>${desc}</p></div>`}

function home(p){const next=p.events[0]||p.programs.find(x=>x.runs===true);return `${head(`Добрый день, ${p.name}`,p.summary)}
<div class="dcw-grid">
 <div class="dcw-card dcw-card--4 dcw-stat"><span>PROGRAMS</span><strong>${p.programs.length}</strong><small>доступных сущностей</small></div>
 <div class="dcw-card dcw-card--4 dcw-stat"><span>EVENTS</span><strong>${p.events.length}</strong><small>доступных сущностей</small></div>
 <div class="dcw-card dcw-card--4 dcw-stat"><span>PROJECTS</span><strong>${p.projects.length}</strong><small>только Dementor Club</small></div>
</div>
<div class="dcw-section"><div class="dcw-section-head"><h2>Моя работа</h2>${source()}</div><div class="dcw-list">${[...p.programs,...p.events].map(entityRow).join('')}</div></div>
<div class="dcw-section"><div class="dcw-section-head"><h2>Следующее</h2></div>${next?`<div class="dcw-callout">${next.title}: ${next.meta||next.content}. Статус: <strong>${next.status}</strong>.</div>`:`<div class="dcw-empty">Нет подтверждённых ближайших occurrence/event. Workspace не создаёт фиктивный календарь.</div>`}</div>`}

function entityRow(e){const route=e.type==='event'?'event':'program';return `<div class="dcw-row" data-open="${route}" data-id="${e.id}"><div class="dcw-row-title"><strong>${e.title}</strong><span class="dcw-row-meta">${e.type} · ${e.delivery||''} · ${e.description}</span></div><div class="dcw-row-actions">${roleBadge(e.assignment)} ${statusBadge(e.uiStatus)} <span class="dcw-arrow">→</span></div></div>`}

function work(p){let entities=[...p.programs.map(x=>({...x,group:'program'})),...p.events.map(x=>({...x,group:'event'})),...p.projects.map(x=>({...x,group:'project'}))];if(state.filter!=='all')entities=entities.filter(x=>x.group===state.filter);return `${head('Моя работа','Список формируется только из активных assignments внутри Dementor Club. Тип пользователя не определяет навигацию.')}
<div class="dcw-filters"><button class="dcw-filter ${state.filter==='all'?'is-active':''}" data-filter="all">ВСЕ</button><button class="dcw-filter ${state.filter==='program'?'is-active':''}" data-filter="program">PROGRAMS</button><button class="dcw-filter ${state.filter==='event'?'is-active':''}" data-filter="event">EVENTS</button><button class="dcw-filter ${state.filter==='project'?'is-active':''}" data-filter="project">PROJECTS</button></div>
<div class="dcw-list">${entities.length?entities.map(entityRow).join(''):`<div class="dcw-empty">В этой группе нет доступных сущностей.</div>`}</div>
<div class="dcw-section"><div class="dcw-callout"><strong>SYSTEM BOUNDARY:</strong> тот же человек может иметь assignments в Modern Pilgrims или Seven Clicks, но этот экран их не запрашивает и не отображает.</div></div>`}

function profile(p){return `${head('Мой профиль','Профиль — отдельная сущность от программ и событий. Роль DEMENTOR scoped к Dementor Club и не является глобальным типом человека.')}
<div class="dcw-profile-grid"><div class="dcw-card"><h2>${p.name}</h2><div class="dcw-badges">${roleBadge('DEMENTOR')} ${statusBadge('ACTIVE')}</div><div class="dcw-field"><span>PERSON</span><strong>${p.name}</strong></div><div class="dcw-field"><span>SYSTEM MEMBERSHIP</span><strong>Dementor Club / active</strong></div><div class="dcw-field"><span>ROLE ASSIGNMENT</span><strong>DEMENTOR / system scope</strong></div></div><div class="dcw-card"><h2>Публичный профиль</h2><p>Doctrine, origin story, areas, indications, methods, quotes — редактируются только когда появится соответствующий permission contract.</p><div class="dcw-action-grid"><button class="dcw-action">Открыть preview</button><button class="dcw-action" disabled>Редактировать профиль</button></div><p class="dcw-source">EDIT DISABLED IN PROTOTYPE</p></div></div>`}

function findProgram(p,id){return p.programs.find(x=>x.id===id)}function findEvent(p,id){return p.events.find(x=>x.id===id)}
function programPage(p,id){const e=findProgram(p,id);if(!e)return `<div class="dcw-empty">Program not found.</div>`;let runBlock='';if(e.runs===true)runBlock=`<div class="dcw-section"><div class="dcw-section-head"><h2>Runs / Occurrences</h2></div><div class="dcw-list"><div class="dcw-row" data-open="run" data-id="${e.id}"><div class="dcw-row-title"><strong>Текущий recurring run</strong><span class="dcw-row-meta">Operational projection · sessions available</span></div><div class="dcw-row-actions">${roleBadge('FACILITATOR')} ${statusBadge('ACTIVE')}<span class="dcw-arrow">→</span></div></div></div></div>`;else if(e.runs==='planned')runBlock=`<div class="dcw-section"><div class="dcw-section-head"><h2>Runs</h2></div><div class="dcw-empty">Structural slot предусмотрен, но скрыт в production до открытия реального набора. Сейчас status = planned.</div></div>`;else runBlock=`<div class="dcw-section"><div class="dcw-section-head"><h2>Runs</h2></div><div class="dcw-empty">Для ${e.delivery} программы run не требуется.</div></div>`;return `<button class="dcw-filter" data-route-back="work">← НАЗАД К MY WORK</button><div class="dcw-entity-hero"><div><div class="dcw-badges">${badge('PROGRAM')} ${badge(e.type)} ${badge(e.delivery)} ${roleBadge(e.assignment)} ${statusBadge(e.uiStatus)}</div><h1>${e.title}</h1><p>${e.description}</p></div><div class="dcw-entity-meta"><div class="dcw-meta-pair"><span>STATUS</span><strong>${e.status}</strong></div><div class="dcw-meta-pair"><span>DELIVERY</span><strong>${e.delivery}</strong></div><div class="dcw-meta-pair"><span>CONTENT</span><strong>${e.content}</strong></div></div></div><div class="dcw-tabs"><button class="dcw-tab is-active">OVERVIEW</button><button class="dcw-tab">CONTENT</button><button class="dcw-tab">MATERIALS</button><button class="dcw-tab">ACCESS</button></div><div class="dcw-grid"><div class="dcw-card dcw-card--8"><h2>О программе</h2><p>${e.content}</p><p>${source()}</p></div><div class="dcw-card dcw-card--4"><h3>Доступные действия</h3><div class="dcw-action-grid"><button class="dcw-action">Открыть public preview</button><button class="dcw-action">Просмотреть структуру</button><button class="dcw-action" disabled>Редактировать</button><button class="dcw-action" disabled>Участники</button></div></div></div>${runBlock}`}

function eventPage(p,id){const e=findEvent(p,id);if(!e)return `<div class="dcw-empty">Event not found.</div>`;return `<button class="dcw-filter" data-route-back="work">← НАЗАД К MY WORK</button><div class="dcw-entity-hero"><div><div class="dcw-badges">${badge('EVENT')} ${roleBadge(e.assignment)} ${statusBadge(e.uiStatus)}</div><h1>${e.title}</h1><p>${e.description}</p></div><div class="dcw-entity-meta"><div class="dcw-meta-pair"><span>STATUS</span><strong>${e.status}</strong></div><div class="dcw-meta-pair"><span>FORMAT</span><strong>${e.meta}</strong></div><div class="dcw-meta-pair"><span>VISIBILITY</span><strong>member details after onboarding</strong></div></div></div><div class="dcw-grid dcw-section"><div class="dcw-card dcw-card--8"><h2>Event state</h2><p>Это отдельная EVENT-сущность. Она не является occurrence программы «НЕ КОМАНДА».</p><div class="dcw-callout">Дата, площадка, duration, price и registration mechanics пока не зафиксированы — поэтому интерфейс их не выдумывает.</div></div><div class="dcw-card dcw-card--4"><h3>Действия</h3><div class="dcw-action-grid"><button class="dcw-action">Preview</button><button class="dcw-action" disabled>Регистрации</button><button class="dcw-action" disabled>Редактировать</button></div></div></div>`}

function runPage(p,id){const e=findProgram(p,id);return `<button class="dcw-filter" data-open="program" data-id="${id}">← НАЗАД К PROGRAM</button><div class="dcw-entity-hero"><div><div class="dcw-badges">${badge('RUN / OCCURRENCE')} ${roleBadge('FACILITATOR')} ${statusBadge('ACTIVE')}</div><h1>${e.title}<br>Recurring Run</h1><p>Универсальная delivery-сущность: PROGRAM → RUN → SESSION.</p></div><div class="dcw-entity-meta"><div class="dcw-meta-pair"><span>SCHEDULE</span><strong>Понедельник · 10:00</strong></div><div class="dcw-meta-pair"><span>TIMEZONE</span><strong>Europe/Madrid</strong></div><div class="dcw-meta-pair"><span>PARTICIPANTS</span><strong>model not approved</strong></div></div></div><div class="dcw-section"><div class="dcw-section-head"><h2>Sessions</h2></div><div class="dcw-list"><div class="dcw-row"><div class="dcw-row-title"><strong>Следующая сессия</strong><span class="dcw-row-meta">Recurring occurrence · exact attendee model not connected</span></div><div class="dcw-row-actions">${statusBadge('ACTIVE')}</div></div></div></div><div class="dcw-section"><div class="dcw-callout">Participants и admission mechanics намеренно не моделируются как реальные данные до утверждения соответствующего workflow.</div></div>`}

function bindDynamic(){document.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>nav(el.dataset.open,el.dataset.id));document.querySelectorAll('[data-filter]').forEach(el=>el.onclick=()=>{state.filter=el.dataset.filter;render()});document.querySelectorAll('[data-route-back]').forEach(el=>el.onclick=()=>nav(el.dataset.routeBack));}

document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();nav(el.dataset.route)}));personSelect.addEventListener('change',()=>setPerson(personSelect.value));
setPerson('valentin');
