from pathlib import Path
import re

app=Path('dementor-lab/src/ui/app.mjs')
s=app.read_text()
s=s.replace("repeat:'повторяет всю цепочку с начала'","repeat:'снова выполняет реакцию, если ответ не принят'",1)
s=s.replace("familyNodes(f).map(n=>`<button type=\"button\" data-add-brain-node=\"${n.type}\">","familyNodes(f).filter(n=>n.type!=='interrupt').map(n=>`<button type=\"button\" data-add-brain-node=\"${n.type}\">",1)
pattern=r"function showHotPatch\(bp\)\{.*?\nfunction showTrace"
replacement="""function hotPatchChainEdges(actor,ids){const set=new Set(ids||[]);return actor.brainGraph.edges.filter(e=>set.has(e.from)&&set.has(e.to))}
function hotPatchRewireOptions(actor,edge){if(!edge)return [];const graph=actor.brainGraph,from=graph.nodes.find(n=>n.id===edge.from),without={...graph,edges:graph.edges.filter(e=>e.id!==edge.id)};return graph.nodes.filter(candidate=>candidate.id!==edge.to&&canConnectNodes(without,from,candidate)).filter(candidate=>{const probe=cloneBrainGraph(graph),probeEdge=probe.edges.find(e=>e.id===edge.id);probeEdge.to=candidate.id;return brainValidation(probe,CRITICISM_IDEA_SCENARIO.openingTrigger).runnable})}
function showRewirePatch(bp,edge){const actor=controller.encounter.actors[bp.actorId],options=hotPatchRewireOptions(actor,edge);overlay.innerHTML=`<div class=\"overlay-card\"><p class=\"kicker\">HOT PATCH / СВЯЗЬ</p><h3>КУДА ПЕРЕНАПРАВИТЬ?</h3><p>${title(actor.brainGraph.nodes.find(n=>n.id===edge.from)?.type)} → …</p><div class=\"patch-grid\">${options.map(n=>`<button data-rewire-target=\"${n.id}\">→ ${title(n.type)}</button>`).join('')}<button data-rewire-back>НАЗАД</button></div></div>`;overlay.hidden=false;overlay.querySelectorAll('[data-rewire-target]').forEach(button=>button.addEventListener('click',()=>controller.patch({kind:'rewire',actorId:bp.actorId,edgeId:edge.id,toNodeId:button.dataset.rewireTarget})));overlay.querySelector('[data-rewire-back]')?.addEventListener('click',()=>showHotPatch(bp))}
function showHotPatch(bp){const actor=controller.encounter.actors[bp.actorId],ids=bp.nodeIds||[],chain=ids.map(id=>title(actor.brainGraph.nodes.find(n=>n.id===id)?.type)).join(' → '),repeat=ids.map(id=>actor.brainGraph.nodes.find(n=>n.id===id)).find(n=>n?.type==='repeat'),impulse=ids.map(id=>actor.brainGraph.nodes.find(n=>n.id===id)).find(n=>familyLabel(n?.type)==='IMPULSE'),chainEdges=hotPatchChainEdges(actor,ids),pauseEdge=chainEdges.find(e=>familyLabel(actor.brainGraph.nodes.find(n=>n.id===e.from)?.type)==='IMPULSE'&&familyLabel(actor.brainGraph.nodes.find(n=>n.id===e.to)?.type)==='REACTION')||chainEdges.find(e=>familyLabel(actor.brainGraph.nodes.find(n=>n.id===e.to)?.type)==='REACTION'),rewireEdge=chainEdges.find(e=>hotPatchRewireOptions(actor,e).length);overlay.innerHTML=`<div class=\"overlay-card\"><p class=\"kicker\">HOT PATCH</p><h3>МОЗГ НАГРЕВАЕТСЯ.</h3><p>Сейчас эта цепочка собирается сделать хуже. Один патч — потом продолжаем тот же разговор.</p><div class=\"chain\">${chain}</div><div class=\"patch-grid\">${repeat?`<button data-patch=\"repeat\">REPEAT ×${repeat.p.count} → ×${Math.max(1,repeat.p.count-1)}</button>`:''}${impulse?`<button data-patch=\"impulse\">${title(impulse.type)} ${impulse.p.weight} → ${Math.max(1,impulse.p.weight-1)}</button>`:''}${pauseEdge?'<button data-patch=\"pause\">ВСТАВИТЬ ПАУЗУ</button>':''}${rewireEdge?'<button data-patch=\"rewire\">СМЕНИТЬ СВЯЗЬ</button>':''}<button data-patch=\"skip\">НИЧЕГО НЕ ТРОГАТЬ</button></div></div>`;overlay.hidden=false;$('[data-patch=repeat]')?.addEventListener('click',()=>controller.patch({kind:'reduce-repeat',actorId:bp.actorId,nodeId:repeat.id}));$('[data-patch=impulse]')?.addEventListener('click',()=>controller.patch({kind:'reduce-impulse',actorId:bp.actorId,nodeId:impulse.id}));$('[data-patch=pause]')?.addEventListener('click',()=>controller.patch({kind:'insert-pause',actorId:bp.actorId,edgeId:pauseEdge.id,nodeId:`pause-${controller.encounter.turn}-${bp.actorId}`}));$('[data-patch=rewire]')?.addEventListener('click',()=>showRewirePatch(bp,rewireEdge));$('[data-patch=skip]').addEventListener('click',()=>{controller.declinePatch();hideOverlay();if(mode==='auto')startAuto()})}
function showTrace"""
out,n=re.subn(pattern,replacement,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'showHotPatch replacement count={n}')
app.write_text(out)

p=Path('dementor-lab/tests/browser-smoke.mjs')
t=p.read_text()
old="await page.locator(`[data-brain-target=\"${reactionId}\"]`).click();await page.waitForTimeout(34);assert.equal(await page.locator('#brain-graph .brain-stack-edge.extra').count(),1,'manual connection renders as one extra bracket over the primary sequence');"
new=old+"\nconst manualEdgeId=await page.locator('#brain-graph .brain-stack-edge.extra').first().getAttribute('data-edge');const reactionHandle=page.locator(`[data-brain-drag=\"${reactionId}\"]`),reactionHandleBox=await reactionHandle.boundingBox(),impulseBox=await impulseWrap.boundingBox();assert.ok(reactionHandleBox&&impulseBox,'drag geometry exists');await page.mouse.move(reactionHandleBox.x+reactionHandleBox.width/2,reactionHandleBox.y+reactionHandleBox.height/2);await page.mouse.down();await page.mouse.move(reactionHandleBox.x+reactionHandleBox.width/2,impulseBox.y+impulseBox.height/2,{steps:4});await page.mouse.up();await page.waitForTimeout(40);assert.equal(await page.locator(`[data-edge=\"${manualEdgeId}\"]`).count(),1,'manual branch survives reorder even when it becomes adjacent');"
if old not in t: raise SystemExit('manual edge smoke target missing')
t=t.replace(old,new,1)
old2="await page.locator('[data-brain-preset=\"always-right\"]').click();assert.equal(await page.locator('#to-setup').isDisabled(),false,'authored preset stays runnable in stack representation');assert.equal(await page.locator('#brain-graph .brain-stack-node').count(),5,'preset nodes render as vertical cards');"
new2="await page.locator('[data-brain-preset=\"always-right\"]').click();await addNode('repeat');assert.equal(await page.locator('#to-setup').isDisabled(),false,'authored preset plus a second repeat stays runnable');assert.equal(await page.locator('#brain-graph .brain-stack-node').count(),6,'preset plus extra repeat renders as vertical cards');"
if old2 not in t: raise SystemExit('preset smoke target missing')
t=t.replace(old2,new2,1)
old3="assert.ok(await page.locator('#brain-graph .brain-stack-node.locked').count()>=1,'non-target cards are locked during one-cause replay');"
new3=old3+"const replayRepeats=page.locator('#brain-graph .brain-stack-node').filter({hasText:'REPEAT'});assert.equal(await replayRepeats.count(),2,'replay fixture contains two same-type nodes');assert.equal(await page.locator('#brain-graph .brain-stack-node.locked').filter({hasText:'REPEAT'}).count(),1,'only the exact suspicious repeat node is unlocked');"
if old3 not in t: raise SystemExit('replay smoke target missing')
t=t.replace(old3,new3,1)
p.write_text(t)
