from pathlib import Path
root=Path('dementor-lab')

p=root/'src/encounter/runtime.mjs'
s=p.read_text()
s=s.replace("export const PAUSE_EFFECTS=Object.freeze({self:{brain:-5,tension:-7,energy:-4},target:{tension:-3,contact:2}});", "export const PAUSE_EFFECTS=Object.freeze({self:{brain:-5,tension:-7,energy:-2},target:{tension:-3,contact:2}});\nexport const REPEAT_FRICTION=Object.freeze({self:{energy:-1,brain:4,tension:4},target:{contact:-2}});")
s=s.replace("function conditionAllows(character,path){return path.every(n=>n.type!=='ifbrain'||Number(character.state.brain)>Number(n.p?.threshold??70))}\nfunction selectPath(character,trigger){", "function conditionAllows(character,path){return path.every(n=>n.type!=='ifbrain'||Number(character.state.brain)>Number(n.p?.threshold??70))}\nfunction reactionContextScore(character,reaction){\n  const s=character.state||{},energy=Number(s.energy||0),brain=Number(s.brain||0),tension=Number(s.tension||0),contact=Number(s.contact||0);\n  if(reaction==='agree')return Math.max(0,60-contact)*.08+Math.max(0,tension-30)*.05;\n  if(reaction==='joke')return Math.max(0,tension-45)*.08;\n  if(reaction==='silent')return Math.max(0,60-energy)*.12+Math.max(0,brain-75)*.05;\n  if(reaction==='pressure')return Math.max(0,brain-28)*.35+Math.max(0,tension-45)*.1;\n  if(reaction==='explain')return Math.max(0,35-brain)*.01;\n  return 0;\n}\nfunction selectPath(character,trigger){")
s=s.replace("if(fam==='REACTION'&&!reaction){reaction=n.type;score+=8}", "if(fam==='REACTION'&&!reaction){reaction=n.type;score+=8+reactionContextScore(character,n.type)}")
s=s.replace("const selfDelta={},targetDelta={};addDelta(selfDelta,REACTION_EFFECTS[chosen.reaction]?.self);addDelta(targetDelta,REACTION_EFFECTS[chosen.reaction]?.target);", "const selfDelta={},targetDelta={};addDelta(selfDelta,REACTION_EFFECTS[chosen.reaction]?.self);addDelta(targetDelta,REACTION_EFFECTS[chosen.reaction]?.target);addDelta(selfDelta,REPEAT_FRICTION.self);addDelta(targetDelta,REPEAT_FRICTION.target);", 1)
p.write_text(s)

p=root/'src/core/model.mjs'
s=p.read_text().replace("repeat:{family:'CONTROL',title:'REPEAT',description:'повторяет ту же реакцию до лимита и завершает ветку; явное согласие собеседника отменяет оставшиеся повторы',defaults:{count:2}},", "repeat:{family:'CONTROL',title:'REPEAT',description:'повторяет ту же реакцию до лимита и завершает ветку; каждый навязчивый повтор дополнительно разгоняет BRAIN/TENSION, а явное согласие отменяет остаток',defaults:{count:2}},")
p.write_text(s)

p=root/'tests/gameplay-regression-selftest.mjs'
s=p.read_text()
s=s.replace("import { createEncounter, predictTurn, executeActorTurn, applyHotPatch, detectBreakpoint, checkTerminal, REACTION_EFFECTS, IMPULSE_EFFECTS, PAUSE_EFFECTS } from '../src/encounter/runtime.mjs';", "import { createEncounter, predictTurn, executeActorTurn, applyHotPatch, detectBreakpoint, checkTerminal, REACTION_EFFECTS, IMPULSE_EFFECTS, PAUSE_EFFECTS, REPEAT_FRICTION } from '../src/encounter/runtime.mjs';")
s=s.replace("assert.ok(PAUSE_EFFECTS.self.energy<=-4,'PAUSE pays a meaningful energy cost for regulation');", "assert.ok(PAUSE_EFFECTS.self.energy<=-2&&PAUSE_EFFECTS.self.energy>-4,'PAUSE remains costly without exhausting calm characters by arithmetic alone');")
s=s.replace("assert.ok(PAUSE_EFFECTS.self.brain<0&&PAUSE_EFFECTS.self.tension<0&&PAUSE_EFFECTS.target.contact>0,'PAUSE remains a strong regulation trade rather than a dead node');", "assert.ok(PAUSE_EFFECTS.self.brain<0&&PAUSE_EFFECTS.self.tension<0&&PAUSE_EFFECTS.target.contact>0,'PAUSE remains a strong regulation trade rather than a dead node');\nassert.ok(REPEAT_FRICTION.self.brain>0&&REPEAT_FRICTION.self.tension>0&&REPEAT_FRICTION.target.contact<0,'forced repetition has its own loop friction so shortening REPEAT can actually help');")
insert="""\n// Branches are contextual decisions, not decorative tie-breaks.\nconst contextualBranch={id:'contextual-branch',nodes:[{id:'t',type:'criticism',p:{}},{id:'j',type:'joke',p:{}},{id:'p',type:'pressure',p:{}}],edges:[edge('cb1','t','j'),edge('cb2','t','p')]};\nassert.equal(predictTurn(encounterWithGraph(contextualBranch,{brain:15})).chosen.reaction,'joke','low BRAIN keeps the volatile branch playful');\nassert.equal(predictTurn(encounterWithGraph(contextualBranch,{brain:45})).chosen.reaction,'pressure','accumulated BRAIN can flip the same graph into pressure');\nconst tiredPeace={id:'tired-peace',nodes:[{id:'t',type:'criticism',p:{}},{id:'a',type:'agree',p:{}},{id:'s',type:'silent',p:{}}],edges:[edge('tp1','t','a'),edge('tp2','t','s')]};\nconst tiredEncounter=encounterWithGraph(tiredPeace);tiredEncounter.actors.A.state.energy=35;assert.equal(predictTurn(tiredEncounter).chosen.reaction,'silent','low ENERGY can turn appeasement into withdrawal');\n"""
s=s.replace("// Missing current Trigger is transparent NO_ACTION, never silent trigger substitution.", insert+"\n// Missing current Trigger is transparent NO_ACTION, never silent trigger substitution.")
p.write_text(s)
