from pathlib import Path
p=Path('dementor-lab/src/ui/app.mjs')
s=p.read_text()
old="function metricRow(label,key){const a=controller?.encounter?.actors.A.state[key]??actors.A.state[key],b=controller?.encounter?.actors.B.state[key]??actors.B.state[key];const danger=(key==='brain'&&(a>=85||b>=85))||(key==='energy'&&(a<=25||b<=25))||(key==='contact'&&(a<=20||b<=20))||(key==='tension'&&(a>=85||b>=85));return `<div class=\"metric ${danger?'danger':''}\"><label>${label}</label><span class=\"bar\"><i style=\"width:${Math.max(0,Math.min(100,a))}%\"></i></span><span class=\"n\">${Math.round(a)}</span><span class=\"n\">${Math.round(b)}</span><span class=\"bar\"><i style=\"width:${Math.max(0,Math.min(100,b))}%\"></i></span></div>`}"
new="function metricDanger(key,value){return (key==='brain'&&value>=85)||(key==='energy'&&value<=25)||(key==='contact'&&value<=20)||(key==='tension'&&value>=85)}\nfunction metricRow(label,key){const a=controller?.encounter?.actors.A.state[key]??actors.A.state[key],b=controller?.encounter?.actors.B.state[key]??actors.B.state[key],dangerA=metricDanger(key,a),dangerB=metricDanger(key,b);return `<div class=\"metric\"><label>${label}</label><div class=\"metric-side a\"><span class=\"bar ${dangerA?'danger':''}\"><i style=\"width:${Math.max(0,Math.min(100,a))}%\"></i></span><span class=\"n\">${Math.round(a)}</span></div><div class=\"metric-side b\"><span class=\"n\">${Math.round(b)}</span><span class=\"bar ${dangerB?'danger':''}\"><i style=\"width:${Math.max(0,Math.min(100,b))}%\"></i></span></div></div>`}"
assert old in s
s=s.replace(old,new)
old="function renderTalk(){if(!controller?.encounter)return;const e=controller.encounter;$('#turn').textContent=e.turn;$('#actor-a-name').textContent=e.actors.A.name.toUpperCase();$('#actor-b-name').textContent=e.actors.B.name.toUpperCase();$('#talk-objective').textContent=`ЦЕЛЬ: ${e.scenario.objectiveLabel} · ${objectiveProgressText(e)}`;$('#metrics').innerHTML=metricRow('ENERGY','energy')+metricRow('BRAIN','brain')+metricRow('TENSION','tension')+metricRow('CONTACT','contact');const transcript=e.transcript.slice(-5);$('#dialogue').innerHTML=transcript.length?transcript.map(x=>`<div class=\"bubble ${x.actorId==='A'?'a':'b'}\"><small>${e.actors[x.actorId].name.toUpperCase()}</small>${x.phrase||'…'}</div>`).join(''):'<p class=\"empty\">Никто ещё ничего не сказал.</p>';const cause=$('#talk-cause'),trace=e.traces.at(-1);if(cause){cause.classList.toggle('empty',!trace);cause.dataset.actor=trace?.actorId||'';cause.innerHTML=talkCauseHtml(trace)}renderTalkStageDirection(trace);$('#next-turn').textContent=mode==='auto'?(autoTimer?'PAUSE':'RESUME'):'NEXT TURN →'}"
new="function renderTalk(){if(!controller?.encounter)return;const e=controller.encounter;$('#turn').textContent=e.turn;$('#actor-a-name').textContent=e.actors.A.name.toUpperCase();$('#actor-b-name').textContent=e.actors.B.name.toUpperCase();$('#talk-objective').textContent=`ЦЕЛЬ: ${e.scenario.objectiveLabel} · ${objectiveProgressText(e)}`;$('#metrics').innerHTML=`<div class=\"metrics-head\"><span>${e.actors.A.name.toUpperCase()}</span><span>${e.actors.B.name.toUpperCase()}</span></div>`+metricRow('ENERGY','energy')+metricRow('BRAIN','brain')+metricRow('TENSION','tension')+metricRow('CONTACT','contact');const dialogue=$('#dialogue'),oldScroll=dialogue.scrollTop,nearBottom=!dialogue.dataset.rendered||dialogue.scrollHeight-dialogue.scrollTop-dialogue.clientHeight<48,transcript=e.transcript;dialogue.innerHTML=transcript.length?transcript.map(x=>`<div class=\"bubble ${x.actorId==='A'?'a':'b'}\"><small>${e.actors[x.actorId].name.toUpperCase()}</small>${x.phrase||'…'}</div>`).join(''):'<p class=\"empty\">Никто ещё ничего не сказал.</p>';dialogue.dataset.rendered='1';requestAnimationFrame(()=>{dialogue.scrollTop=nearBottom?dialogue.scrollHeight:oldScroll});const cause=$('#talk-cause'),trace=e.traces.at(-1);if(cause){cause.classList.toggle('empty',!trace);cause.dataset.actor=trace?.actorId||'';cause.innerHTML=talkCauseHtml(trace)}renderTalkStageDirection(trace);$('#next-turn').textContent=mode==='auto'?(autoTimer?'PAUSE':'RESUME'):'NEXT TURN →'}"
assert old in s
s=s.replace(old,new)
old="host.innerHTML=`${triggerHubHtml()}<section class=\"brain-behavior-block\" data-behavior-block>${brainReadableRouteHtml()}<div class=\"brain-behavior-head\"><small>РЕДАКТОР</small><strong>ИЗ ЧЕГО ЭТО СОБРАНО</strong><p>Нажми на узел, чтобы изменить параметр, связь или порядок.</p></div><svg class=\"brain-stack-links\" aria-hidden=\"true\"></svg><div class=\"brain-stack-list\">${body.map(n=>projectedBrainNodeHtml(n,route)).join('')}</div></section>`"
new="host.innerHTML=`${triggerHubHtml()}<section class=\"brain-behavior-block\" data-behavior-block><div class=\"brain-behavior-head\"><small>РЕДАКТОР</small><strong>ИЗ ЧЕГО ЭТО СОБРАНО</strong><p>Нажми на узел, чтобы изменить параметр, связь или порядок.</p></div><svg class=\"brain-stack-links\" aria-hidden=\"true\"></svg><div class=\"brain-stack-list\">${body.map(n=>projectedBrainNodeHtml(n,route)).join('')}</div>${brainReadableRouteHtml()}</section>`"
assert old in s
s=s.replace(old,new)
old="const box=host.getBoundingClientRect(),byId=Object.fromEntries"
new="const box=svg.getBoundingClientRect(),byId=Object.fromEntries"
assert old in s
s=s.replace(old,new)
p.write_text(s)
