from pathlib import Path
p=Path('dementor-lab/src/ui/app.mjs')
s=p.read_text()
def rep(old,new,label):
    global s
    if old not in s: raise SystemExit(f'{label} not found')
    s=s.replace(old,new,1)

rep("import { CRITICISM_IDEA_SCENARIO, createCriticismActors } from '../scenarios/criticism-idea.mjs';", "import { CRITICISM_IDEA_SCENARIO, createCriticismActors } from '../scenarios/criticism-idea.mjs';\nimport { DIRECT_ANSWER_SCENARIO, createDirectAnswerActors } from '../scenarios/direct-answer.mjs';", 'import')
rep("let opponentProfile=createOpponentProfile(opponentSeed);\nlet mode='auto',actors=createCriticismActors({opponentProfile,playerName:playerName||'Гена'}),controller=null,autoTimer=null;", "let opponentProfile=createOpponentProfile(opponentSeed);\nlet currentScenario=CRITICISM_IDEA_SCENARIO;\nlet mode='auto',actors=createCriticismActors({opponentProfile,playerName:playerName||'Гена'}),controller=null,autoTimer=null;", 'scenario state')
rep("function show(screen){app.dataset.screen=screen;topStatus.textContent=screen.toUpperCase();$$('.screen').forEach(el=>el.hidden=el.dataset.view!==screen);$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===screen));if(screen==='brain'){renderBrain();$('#replay-note').hidden=!replayMode}if(screen==='setup'){renderScenarioCopy();renderOpponentCard()}if(screen==='talk'){renderScenarioCopy();renderTalk()}}", "function show(screen){app.dataset.screen=screen;topStatus.textContent=screen.toUpperCase();$$('.screen').forEach(el=>el.hidden=el.dataset.view!==screen);$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===screen));if(screen==='brain'){renderBrain();$('#replay-note').hidden=!replayMode}if(screen==='setup'){renderScenarioSelector();renderScenarioCopy();renderOpponentCard()}if(screen==='talk'){renderScenarioCopy();renderTalk()}}", 'show')
rep("function resetActors(){actors=createCriticismActors({opponentProfile,playerName:playerDisplayName()});actors.A.brainGraph=cloneBrainGraph(currentBrainGraph);actors.A.visual={...(actors.A.visual||{}),characterId:currentCharacterId,appearance:playerAppearance()};actors.B.visual={...(actors.B.visual||{}),characterId:opponentProfile.baseCharacterId,appearance:opponentAppearance(),opponentPresetId:opponentProfile.presetId}}", "function resetActors(){actors=currentScenario.id==='direct-answer'?createDirectAnswerActors({playerGraph:currentBrainGraph,playerName:playerDisplayName(),opponentName:opponentProfile.name}):createCriticismActors({opponentProfile,playerName:playerDisplayName()});actors.A.brainGraph=cloneBrainGraph(currentBrainGraph);actors.A.visual={...(actors.A.visual||{}),characterId:currentCharacterId,appearance:playerAppearance()};actors.B.visual={...(actors.B.visual||{}),characterId:opponentProfile.baseCharacterId,appearance:opponentAppearance(),opponentPresetId:currentScenario.id==='direct-answer'?'DIRECT_ANSWER':opponentProfile.presetId}}", 'resetActors')
rep("function renderScenarioCopy(){const s=CRITICISM_IDEA_SCENARIO;$('#scenario-title')&&($('#scenario-title').textContent=s.title);$('#scenario-premise')&&($('#scenario-premise').textContent=s.premise);$('#scenario-objective')&&($('#scenario-objective').textContent=s.objectiveLabel);$('#scenario-end')&&($('#scenario-end').textContent=`${s.turnLimit} РАУНДОВ ИЛИ РАЗВАЛ`);$('#talk-scenario-title')&&($('#talk-scenario-title').textContent=s.title);$('#talk-objective')&&($('#talk-objective').textContent=`ЦЕЛЬ: ${s.objectiveLabel}`)}", "function scenarioObjectiveCopy(s){if(s.objective==='direct-answer')return `${s.objectiveRules.requiredOpponentCounterpoints} ПРЯМЫХ ОТВЕТА + CONTACT ≥${s.objectiveRules.minRelationshipContact}`;return `${s.objectiveLabel} · CONTACT ≥${s.objectiveRules.minRelationshipContact}`}\nfunction renderScenarioSelector(){$$('[data-scenario]').forEach(b=>{const active=(b.dataset.scenario==='direct-answer')===(currentScenario.id==='direct-answer');b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));b.disabled=Boolean(replayMode||baselineEncounter)})}\nfunction selectScenario(id){if(replayMode||baselineEncounter)return;currentScenario=id==='direct-answer'?DIRECT_ANSWER_SCENARIO:CRITICISM_IDEA_SCENARIO;resetActors();renderScenarioSelector();renderScenarioCopy();renderOpponentCard()}\nfunction renderScenarioCopy(){const s=currentScenario;$('#scenario-title')&&($('#scenario-title').textContent=s.title);$('#scenario-premise')&&($('#scenario-premise').textContent=s.premise);$('#scenario-objective')&&($('#scenario-objective').textContent=scenarioObjectiveCopy(s));$('#scenario-end')&&($('#scenario-end').textContent=`${s.turnLimit} РАУНДОВ ИЛИ РАЗВАЛ`);$('#talk-scenario-title')&&($('#talk-scenario-title').textContent=s.title)}", 'scenario copy')
rep("function renderOpponentCard(){const card=$('#opponent-card');if(!card)return;card.dataset.preset=opponentProfile.presetId;card.dataset.character=opponentProfile.baseCharacterId;$('#opponent-name').textContent=opponentProfile.name.toUpperCase();$('#opponent-preset').textContent=opponentProfile.presetLabel;$('#opponent-description').textContent=opponentProfile.description;$('#opponent-seed').textContent=`SEED ${String(opponentSeed).slice(0,12)}`}", "function renderOpponentCard(){const card=$('#opponent-card');if(!card)return;const direct=currentScenario.id==='direct-answer';card.dataset.preset=direct?'DIRECT_ANSWER':opponentProfile.presetId;card.dataset.character=opponentProfile.baseCharacterId;$('#opponent-name').textContent=opponentProfile.name.toUpperCase();$('#opponent-preset').textContent=direct?'УХОДИТ ОТ ОТВЕТА':opponentProfile.presetLabel;$('#opponent-description').textContent=direct?'На объяснение отвечает по существу. На шутку уходит в шутку, на молчание — в молчание, на давление — давит в ответ.':opponentProfile.description;$('#opponent-seed').textContent=`SEED ${String(opponentSeed).slice(0,12)}`}", 'opponent card')
rep("function currentValidation(){return brainValidation(currentBrainGraph,CRITICISM_IDEA_SCENARIO.openingTrigger)}", "function currentValidation(){return brainValidation(currentBrainGraph,currentScenario.openingTrigger)}", 'validation')
rep("function renderTalk(){if(!controller?.encounter)return;const e=controller.encounter;$('#turn').textContent=e.turn;$('#actor-a-name').textContent=e.actors.A.name.toUpperCase();$('#actor-b-name').textContent=e.actors.B.name.toUpperCase();$('#metrics').innerHTML=metricRow('ENERGY','energy')+metricRow('BRAIN','brain')+metricRow('TENSION','tension')+metricRow('CONTACT','contact');const transcript=e.transcript.slice(-5);", "function objectiveProgressText(e){const contact=Math.round(Math.min(e.actors.A.state.contact,e.actors.B.state.contact));if(e.scenario.objective==='direct-answer'){const answers=e.traces.filter(t=>t.actorId==='B'&&t.event?.type==='COUNTERPOINT').length,required=e.scenario.objectiveRules.requiredOpponentCounterpoints,min=e.scenario.objectiveRules.minRelationshipContact;return `ОТВЕТЫ ${answers}/${required} · CONTACT ${contact}/${min}`}return `CONTACT ${contact}/${e.scenario.objectiveRules.minRelationshipContact}`}\nfunction renderTalk(){if(!controller?.encounter)return;const e=controller.encounter;$('#turn').textContent=e.turn;$('#actor-a-name').textContent=e.actors.A.name.toUpperCase();$('#actor-b-name').textContent=e.actors.B.name.toUpperCase();$('#talk-objective').textContent=`ЦЕЛЬ: ${e.scenario.objectiveLabel} · ${objectiveProgressText(e)}`;$('#metrics').innerHTML=metricRow('ENERGY','energy')+metricRow('BRAIN','brain')+metricRow('TENSION','tension')+metricRow('CONTACT','contact');const transcript=e.transcript.slice(-5);", 'renderTalk')
rep("controller=new VerticalSliceController({scenario:CRITICISM_IDEA_SCENARIO,actors,renderers:talkRenderers,onEvent:handleEvent})", "controller=new VerticalSliceController({scenario:currentScenario,actors,renderers:talkRenderers,onEvent:handleEvent})", 'controller scenario')
rep("return brainValidation(probe,CRITICISM_IDEA_SCENARIO.openingTrigger).runnable", "return brainValidation(probe,currentScenario.openingTrigger).runnable", 'rewire validation')
rep("$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b))}));", "$$('[data-scenario]').forEach(b=>b.addEventListener('click',()=>selectScenario(b.dataset.scenario)));$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b))}));", 'scenario events')
rep("resetActors();syncPlayerName();syncCharacterSwitch();await mountCharacterAssets();renderScenarioCopy();show('person');", "resetActors();syncPlayerName();syncCharacterSwitch();await mountCharacterAssets();renderScenarioSelector();renderScenarioCopy();show('person');", 'init')
p.write_text(s)
