from pathlib import Path

root=Path('dementor-lab')

p=root/'src/render/character-renderer.mjs'
s=p.read_text()
s=s.replace("export function resolveVisualState(character={}){const derived=visualStateFromMetrics(character.state||{}),override=character.face||{};return {...derived,...override,motion:{...derived.motion,...(override.motion||{})}}}", "export function resolveVisualState(character={}){const derived=visualStateFromMetrics(character.state||{}),override=character.face||{};return {...derived,...override,motion:{...derived.motion,...(override.motion||{})}}}\nexport function reactionCueFromDelta(delta={}){\n  const brain=Number(delta.brain||0),tension=Number(delta.tension||0),contact=Number(delta.contact||0),energy=Number(delta.energy||0);\n  let kind='steady',strength=0;\n  const candidates=[\n    ['overheat',Math.max(0,brain)/18],\n    ['tension',Math.max(0,tension)/14],\n    ['withdraw',Math.max(0,-contact)/12],\n    ['connect',Math.max(0,contact)/12],\n    ['relief',Math.max(0,-tension)/12],\n    ['fatigue',Math.max(0,-energy)/16]\n  ];\n  for(const [next,value] of candidates)if(value>strength){kind=next;strength=value}\n  return {kind,strength:Math.max(0,Math.min(1,strength))};\n}\nexport function faceOverrideFromReactionCue(cue={}){\n  const strength=Number(cue.strength||0);if(strength<=0)return {};\n  if(cue.kind==='overheat')return {eyes:strength>.55?'overheat':'tense',brows:'tense',motion:{headInstability:.35+.65*strength,gestureSharpness:.25+.5*strength}};\n  if(cue.kind==='tension')return {brows:strength>.55?'angry':'tense',mouth:'tense',motion:{gestureSharpness:.3+.7*strength}};\n  if(cue.kind==='withdraw')return {eyes:'tense',mouth:'tense',motion:{orientToPartner:-.25-.5*strength}};\n  if(cue.kind==='connect')return {mouth:'soft',motion:{orientToPartner:.25+.5*strength}};\n  if(cue.kind==='relief')return {brows:'neutral',mouth:'soft',motion:{orientToPartner:.15+.25*strength}};\n  if(cue.kind==='fatigue')return {eyes:'sleepy',motion:{amplitude:Math.max(.45,1-.45*strength),headDrop:.25+.75*strength}};\n  return {};\n}")
p.write_text(s)

p=root/'src/ui/app.mjs'
s=p.read_text()
s=s.replace("import { CharacterRenderer, APPEARANCE_LAYERS } from '../render/character-renderer.mjs';", "import { CharacterRenderer, APPEARANCE_LAYERS, reactionCueFromDelta, faceOverrideFromReactionCue } from '../render/character-renderer.mjs';")
s=s.replace("let baselineEncounter=null,replayMode=false,firstRunConfig=null,replayTargetNodeId=null,previewRenderer=null;", "let baselineEncounter=null,replayMode=false,firstRunConfig=null,replayTargetNodeId=null,previewRenderer=null,talkRenderers=null;")
s=s.replace("function makeController(){const specA=characterSpec(currentCharacterId),specB=characterSpec(opponentProfile.baseCharacterId);const rendererA=new CharacterRenderer({side:'A',root:$('#actor-a'),rigFallback:specA.rigFallback}),rendererB=new CharacterRenderer({side:'B',root:$('#actor-b'),rigFallback:specB.rigFallback});controller=new VerticalSliceController({scenario:CRITICISM_IDEA_SCENARIO,actors,renderers:{A:rendererA,B:rendererB},onEvent:handleEvent})}", "function makeController(){const specA=characterSpec(currentCharacterId),specB=characterSpec(opponentProfile.baseCharacterId);const rendererA=new CharacterRenderer({side:'A',root:$('#actor-a'),rigFallback:specA.rigFallback}),rendererB=new CharacterRenderer({side:'B',root:$('#actor-b'),rigFallback:specB.rigFallback});talkRenderers={A:rendererA,B:rendererB};controller=new VerticalSliceController({scenario:CRITICISM_IDEA_SCENARIO,actors,renderers:talkRenderers,onEvent:handleEvent})}\nfunction clearTalkReactionClasses(){for(const id of ['actor-a','actor-b']){const root=$(`#${id}`);if(!root)continue;root.classList.remove('reaction-hit','reaction-speaker','reaction-overheat','reaction-tension','reaction-withdraw','reaction-connect','reaction-relief','reaction-fatigue');root.removeAttribute('data-reaction-cue')}}\nfunction renderCharacterReaction(trace){if(!trace||!controller?.encounter||!talkRenderers)return;clearTalkReactionClasses();const speakerId=trace.actorId,targetId=speakerId==='A'?'B':'A',selfCue=reactionCueFromDelta(trace.metricDeltas?.self||{}),targetCue=reactionCueFromDelta(trace.metricDeltas?.target||{});for(const [id,cue,role] of [[speakerId,selfCue,'speaker'],[targetId,targetCue,'target']]){const actor=controller.encounter.actors[id],renderer=talkRenderers[id],root=$(`#actor-${id.toLowerCase()}`);if(!actor||!renderer||!root)continue;renderer.render({...actor,face:faceOverrideFromReactionCue(cue)});root.dataset.reactionCue=cue.kind;root.classList.add(role==='speaker'?'reaction-speaker':'reaction-hit');if(cue.kind!=='steady')root.classList.add(`reaction-${cue.kind}`)}}")
s=s.replace("function handleEvent(evt){if(evt.type==='TURN'){renderDelta(evt.trace);renderTalk()}", "function handleEvent(evt){if(evt.type==='TURN'){renderDelta(evt.trace);renderTalk();renderCharacterReaction(evt.trace)}")
p.write_text(s)

p=root/'character.css'
s=p.read_text()+"\n/* TALK reaction projection: visual feedback derives from the same trace deltas as text feedback. */\n.talk .character-slot.small{transition:transform .18s ease,opacity .18s ease,filter .18s ease}\n.talk .character-slot.reaction-speaker{z-index:2}\n.talk .character-slot.reaction-hit{z-index:3}\n.talk .character-slot.reaction-overheat{filter:contrast(1.08);animation:talk-overheat-hit .22s steps(2,end) 2}\n.talk .character-slot.reaction-tension{animation:talk-tension-hit .26s ease-out 1}\n.talk .character-slot.reaction-withdraw{opacity:.78;transform:translateX(var(--reaction-away,0)) scale(.97)}\n.actor-a .character-slot.reaction-withdraw{--reaction-away:-5px}.actor-b .character-slot.reaction-withdraw{--reaction-away:5px}\n.talk .character-slot.reaction-connect{transform:translateX(var(--reaction-toward,0)) scale(1.02)}\n.actor-a .character-slot.reaction-connect{--reaction-toward:4px}.actor-b .character-slot.reaction-connect{--reaction-toward:-4px}\n.talk .character-slot.reaction-relief{transform:translateY(2px)}\n.talk .character-slot.reaction-fatigue{transform:translateY(5px);opacity:.88}\n@keyframes talk-overheat-hit{0%{translate:-1px 0}100%{translate:1px 0}}\n@keyframes talk-tension-hit{0%{scale:1}45%{scale:1.025}100%{scale:1}}\n@media(prefers-reduced-motion:reduce){.talk .character-slot.reaction-overheat,.talk .character-slot.reaction-tension{animation:none}}\n"
p.write_text(s)

p=root/'tests/character-renderer-selftest.mjs'
s=p.read_text()
s=s.replace("import { visualStateFromMetrics, resolveVisualState, isNumberedVariantId, legacyVariantLayerDisplay } from '../src/render/character-renderer.mjs';", "import { visualStateFromMetrics, resolveVisualState, reactionCueFromDelta, faceOverrideFromReactionCue, isNumberedVariantId, legacyVariantLayerDisplay } from '../src/render/character-renderer.mjs';")
s=s.replace("assert.ok(override.motion.headInstability>0,'other derived motion survives partial override');", "assert.ok(override.motion.headInstability>0,'other derived motion survives partial override');\n\nconst cueOverheat=reactionCueFromDelta({brain:12,tension:3});\nassert.equal(cueOverheat.kind,'overheat','brain delta projects to an immediate overheat cue');\nassert.ok(cueOverheat.strength>0);\nconst cueWithdraw=reactionCueFromDelta({contact:-8});\nassert.equal(cueWithdraw.kind,'withdraw','contact loss projects to visible withdrawal');\nassert.ok(faceOverrideFromReactionCue(cueWithdraw).motion.orientToPartner<0);\nconst cueConnect=reactionCueFromDelta({contact:7,tension:-2});\nassert.equal(cueConnect.kind,'connect','contact gain projects to visible approach');\nassert.equal(faceOverrideFromReactionCue(cueConnect).mouth,'soft');")
p.write_text(s)

p=root/'tests/browser-smoke.mjs'
s=p.read_text()
needle="assert.ok((await page.locator('#talk-cause').textContent()).includes('СЛЕДУЮЩИЙ МОЗГ'),'TALK makes the next brain input visible');"
replace=needle+"assert.equal(await page.locator('#actor-a[data-reaction-cue], #actor-b[data-reaction-cue]').count(),2,'both characters expose trace-derived visual reaction cues');assert.ok(await page.locator('#actor-a.reaction-hit, #actor-b.reaction-hit').count()===1,'the listener is visually marked as the reaction target');"
s=s.replace(needle,replace)
p.write_text(s)
