from pathlib import Path
root=Path('dementor-lab')

p=root/'src/ui/app.mjs'
s=p.read_text()
old="function renderTalk(){if(!controller?.encounter)return;const e=controller.encounter;$('#turn').textContent=e.turn;$('#actor-a-name').textContent=e.actors.A.name.toUpperCase();$('#actor-b-name').textContent=e.actors.B.name.toUpperCase();$('#metrics').innerHTML=metricRow('ENERGY','energy')+metricRow('BRAIN','brain')+metricRow('TENSION','tension')+metricRow('CONTACT','contact');const transcript=e.transcript.slice(-5);$('#dialogue').innerHTML=transcript.length?transcript.map(x=>`<div class=\"bubble ${x.actorId==='A'?'a':'b'}\"><small>${e.actors[x.actorId].name.toUpperCase()}</small>${x.phrase||'…'}</div>`).join(''):'<p class=\"empty\">Никто ещё ничего не сказал.</p>';const cause=$('#talk-cause'),trace=e.traces.at(-1);if(cause){cause.classList.toggle('empty',!trace);cause.dataset.actor=trace?.actorId||'';cause.innerHTML=talkCauseHtml(trace)}$('#next-turn').textContent=mode==='auto'?(autoTimer?'PAUSE':'RESUME'):'NEXT TURN →'}"
new="function renderTalk(){if(!controller?.encounter)return;const e=controller.encounter;$('#turn').textContent=e.turn;$('#actor-a-name').textContent=e.actors.A.name.toUpperCase();$('#actor-b-name').textContent=e.actors.B.name.toUpperCase();$('#metrics').innerHTML=metricRow('ENERGY','energy')+metricRow('BRAIN','brain')+metricRow('TENSION','tension')+metricRow('CONTACT','contact');const transcript=e.transcript.slice(-5);$('#dialogue').innerHTML=transcript.length?transcript.map(x=>`<div class=\"bubble ${x.actorId==='A'?'a':'b'}\"><small>${e.actors[x.actorId].name.toUpperCase()}</small>${x.phrase||'…'}</div>`).join(''):'<p class=\"empty\">Никто ещё ничего не сказал.</p>';const cause=$('#talk-cause'),trace=e.traces.at(-1);if(cause){cause.classList.toggle('empty',!trace);cause.dataset.actor=trace?.actorId||'';cause.innerHTML=talkCauseHtml(trace)}renderTalkStageDirection(trace);$('#next-turn').textContent=mode==='auto'?(autoTimer?'PAUSE':'RESUME'):'NEXT TURN →'}\nfunction renderTalkStageDirection(trace){const arena=$('.arena'),a=$('.actor-a'),b=$('.actor-b'),turn=$('.turn');if(!arena||!a||!b||!turn)return;a.classList.remove('is-speaking','is-target');b.classList.remove('is-speaking','is-target');arena.removeAttribute('data-speaker');arena.removeAttribute('data-target');arena.removeAttribute('data-flow');turn.removeAttribute('data-flow-label');if(!trace)return;const speaker=trace.actorId==='B'?'B':'A',target=speaker==='A'?'B':'A',speakerEl=speaker==='A'?a:b,targetEl=target==='A'?a:b;speakerEl.classList.add('is-speaking');targetEl.classList.add('is-target');arena.dataset.speaker=speaker;arena.dataset.target=target;arena.dataset.flow=`${speaker}-${target}`;turn.dataset.flowLabel=`${speaker} → ${target}`}"
if old not in s: raise SystemExit('renderTalk target not found')
s=s.replace(old,new)
p.write_text(s)

p=root/'styles.css'
s=p.read_text()+"\n/* TALK stage direction: one arena, one visible flow. */\n.talk .arena{position:relative}\n.talk .actor{position:relative;transition:opacity .18s ease,transform .18s ease}\n.talk .actor.is-speaking{z-index:4}\n.talk .actor.is-speaking>strong{display:inline-block;background:var(--acid);border:2px solid var(--ink);padding:4px 7px;margin-top:-9px}\n.talk .actor.is-speaking::before{content:'ГОВОРИТ';position:absolute;left:50%;top:4px;translate:-50% 0;z-index:6;padding:3px 5px;background:var(--ink);color:var(--paper);font:900 8px/1 monospace;letter-spacing:.05em}\n.talk .actor.is-target::after{content:'ПОЛУЧАЕТ';position:absolute;left:50%;top:4px;translate:-50% 0;z-index:6;padding:3px 5px;border:1px solid var(--ink);background:var(--paper);font:900 8px/1 monospace;letter-spacing:.05em}\n.talk .arena[data-flow] .turn{position:relative;z-index:7;min-height:74px;display:grid;place-items:center;align-content:center}\n.talk .arena[data-flow] .turn::after{content:attr(data-flow-label);display:block;margin-top:5px;padding:5px 4px;border-top:2px solid var(--ink);border-bottom:2px solid var(--ink);background:var(--acid);font:900 10px/1 monospace;white-space:nowrap}\n.talk .arena[data-flow='A-B'] .actor-a,.talk .arena[data-flow='B-A'] .actor-b{transform:translateX(var(--talk-speaker-nudge,0))}\n.talk .arena[data-flow='A-B'] .actor-a{--talk-speaker-nudge:3px}.talk .arena[data-flow='B-A'] .actor-b{--talk-speaker-nudge:-3px}\n.talk .arena[data-flow='A-B'] .actor-b,.talk .arena[data-flow='B-A'] .actor-a{opacity:.9}\n@media(max-width:430px){.talk .actor.is-speaking::before,.talk .actor.is-target::after{top:2px;font-size:7px;padding:3px 4px}.talk .arena[data-flow] .turn::after{font-size:9px}}\n@media(prefers-reduced-motion:reduce){.talk .actor{transition:none}}\n"
p.write_text(s)

p=root/'tests/browser-smoke.mjs'
s=p.read_text()
needle="assert.match(await page.locator('#delta .delta-feedback small').textContent(),/ГОВОРЯЩИЙ:|СОБЕСЕДНИК:/,'exact trace deltas remain available as second-level detail');"
insert=needle+"assert.match(await page.locator('.arena').getAttribute('data-flow'),/^(A-B|B-A)$/,'arena exposes real speaker to listener flow');assert.equal(await page.locator('.actor.is-speaking').count(),1,'arena has exactly one visible speaker');assert.equal(await page.locator('.actor.is-target').count(),1,'arena has exactly one visible listener target');assert.match(await page.locator('.turn').getAttribute('data-flow-label'),/^(A → B|B → A)$/,'center turn marker points toward the next brain');"
if needle not in s: raise SystemExit('browser needle not found')
s=s.replace(needle,insert)
p.write_text(s)
