import { VerticalSliceController } from '../app/vertical-slice-controller.mjs';
import { CRITICISM_IDEA_SCENARIO, createCriticismActors } from '../scenarios/criticism-idea.mjs';
import { compareRuns } from '../encounter/result.mjs';
import { NODE_SPECS } from '../core/model.mjs';
import { familyOf, canConnectNodes } from '../core/graph.mjs';
import { CharacterRenderer, APPEARANCE_LAYERS } from '../render/character-renderer.mjs';
import { BRAIN_PRESETS, BLANK_BRAIN, cloneBrainGraph, brainPreset } from './brain-presets.mjs';
import { BRAIN_FAMILY_ORDER, ensureBrainPositions, addBrainNode, removeBrainNode, connectBrainNodes, compatibleBrainTargets, brainValidation, familyNodes } from './brain-constructor.mjs';
import { CHARACTER_REGISTRY, characterSpec, characterAssetText, loadCharacterContract, SHARED_APPEARANCE_LAYERS, CHARACTER_OWNED_LAYERS, SHARED_APPEARANCE_CATEGORIES, CHARACTER_OWNED_CATEGORIES, appearanceForCharacter, variantOptions, variantKey, hasVariantContract } from '../render/character-registry.mjs';
import { createOpponentProfile, freshOpponentSeed } from '../opponent/generator.mjs';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const app=$('#app'),overlay=$('#overlay'),topStatus=$('#top-status');
const VARIANT_PART_CATEGORY=Object.freeze({hat:'hat',glasses:'glasses',beard:'facialHair',accessory:'accessory',outfit:'outfit',shoes:'shoes'});
const EMPTY_SHARED_VARIANTS=()=>({hatVariant:null,glassesVariant:null,facialHairVariant:null,accessoryVariant:null});
const EMPTY_OWNED_VARIANTS=()=>({outfitVariant:null,shoesVariant:null});
const EMPTY_COLORS=()=>({outfitPrimary:null,outfitSecondary:null,shoesPrimary:null});
await Promise.allSettled(Object.keys(CHARACTER_REGISTRY).map(id=>loadCharacterContract(id)));

let currentCharacterId='character-01';
let sharedAppearance={hat:true,glasses:true,beard:true,accessory:true,...EMPTY_SHARED_VARIANTS()};
let ownedAppearance={'character-01':{outfit:true,shoes:true,...EMPTY_OWNED_VARIANTS()},'character-02':{outfit:true,shoes:true,...EMPTY_OWNED_VARIANTS()}};
let appearanceColors={'character-01':EMPTY_COLORS(),'character-02':EMPTY_COLORS()};
let activeAppearanceCategory='hat';
const PLAYER_NAME_KEY='dementor-lab.playerName';
let playerName=(localStorage.getItem(PLAYER_NAME_KEY)||'').trim().slice(0,24);
const explicitSeed=new URLSearchParams(location.search).get('seed');
let opponentSeed=explicitSeed||freshOpponentSeed();
let opponentProfile=createOpponentProfile(opponentSeed);
let mode='auto',actors=createCriticismActors({opponentProfile,playerName:playerName||'Гена'}),controller=null,autoTimer=null;
let baselineEncounter=null,replayMode=false,firstRunConfig=null,replayTargetNodeId=null,previewRenderer=null;
let currentBrainGraph=structuredClone(actors.A.brainGraph),activeBrainNodeId=null,brainConnectFromId=null,activeBrainPresetId=null;
ensureBrainPositions(currentBrainGraph);

function playerAppearance(){return appearanceForCharacter(currentCharacterId,sharedAppearance,ownedAppearance[currentCharacterId],appearanceColors[currentCharacterId])}
function opponentAppearance(){return appearanceForCharacter(opponentProfile.baseCharacterId,opponentProfile.sharedAppearance,opponentProfile.ownedAppearance,opponentProfile.colors)}
async function fetchAsset(id){const cached=characterAssetText(id);if(cached)return cached;const spec=characterSpec(id);return fetch(spec.asset).then(r=>{if(!r.ok)throw new Error(`Character asset ${id} ${r.status}`);return r.text()})}
async function mountAsset(rootId,id){const root=$(`#${rootId}`),spec=characterSpec(id);root.innerHTML=await fetchAsset(id);root.dataset.character=id;root.querySelector('svg')?.setAttribute('aria-hidden','true');return new CharacterRenderer({side:rootId==='actor-b'?'B':'A',root,rigFallback:spec.rigFallback})}
async function mountCharacterAssets(){previewRenderer=await mountAsset('person-preview',currentCharacterId);await mountAsset('actor-a',currentCharacterId);await mountAsset('actor-b',opponentProfile.baseCharacterId);syncAppearancePanel();renderPreview();renderOpponentCard()}
async function remountPlayerCharacter(){previewRenderer=await mountAsset('person-preview',currentCharacterId);await mountAsset('actor-a',currentCharacterId);syncCharacterSwitch();syncAppearancePanel();resetActors();renderPreview()}
async function remountOpponent(){await mountAsset('actor-b',opponentProfile.baseCharacterId);resetActors();renderOpponentCard()}
function show(screen){app.dataset.screen=screen;topStatus.textContent=screen.toUpperCase();$$('.screen').forEach(el=>el.hidden=el.dataset.view!==screen);$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===screen));if(screen==='brain'){renderBrain();$('#replay-note').hidden=!replayMode}if(screen==='setup'){renderScenarioCopy();renderOpponentCard()}if(screen==='talk'){renderScenarioCopy();renderTalk()}}
function playerDisplayName(){return playerName.trim()||'Гена'}
function resetActors(){actors=createCriticismActors({opponentProfile,playerName:playerDisplayName()});actors.A.brainGraph=cloneBrainGraph(currentBrainGraph);actors.A.visual={...(actors.A.visual||{}),characterId:currentCharacterId,appearance:playerAppearance()};actors.B.visual={...(actors.B.visual||{}),characterId:opponentProfile.baseCharacterId,appearance:opponentAppearance(),opponentPresetId:opponentProfile.presetId}}
function renderPreview(){previewRenderer?.render({state:actors.A.state,face:{},visual:{characterId:currentCharacterId,appearance:playerAppearance()}})}
function renderScenarioCopy(){const s=CRITICISM_IDEA_SCENARIO;$('#scenario-title')&&($('#scenario-title').textContent=s.title);$('#scenario-premise')&&($('#scenario-premise').textContent=s.premise);$('#scenario-objective')&&($('#scenario-objective').textContent=s.objectiveLabel);$('#scenario-end')&&($('#scenario-end').textContent=`${s.turnLimit} РАУНДОВ ИЛИ РАЗВАЛ`);$('#talk-scenario-title')&&($('#talk-scenario-title').textContent=s.title);$('#talk-objective')&&($('#talk-objective').textContent=`ЦЕЛЬ: ${s.objectiveLabel}`)}
function syncPlayerName(){const input=$('#player-name');if(input&&input.value!==playerName)input.value=playerName;const next=$('#to-brain');if(next)next.disabled=!playerName.trim()}
function setPlayerName(value){playerName=String(value||'').slice(0,24);const stored=playerName.trim();if(stored)localStorage.setItem(PLAYER_NAME_KEY,stored);else localStorage.removeItem(PLAYER_NAME_KEY);resetActors();syncPlayerName()}
function renderOpponentCard(){const card=$('#opponent-card');if(!card)return;card.dataset.preset=opponentProfile.presetId;card.dataset.character=opponentProfile.baseCharacterId;$('#opponent-name').textContent=opponentProfile.name.toUpperCase();$('#opponent-preset').textContent=opponentProfile.presetLabel;$('#opponent-description').textContent=opponentProfile.description;$('#opponent-seed').textContent=`SEED ${String(opponentSeed).slice(0,12)}`}
async function rerollOpponent(){if(replayMode||baselineEncounter)return;opponentSeed=freshOpponentSeed();opponentProfile=createOpponentProfile(opponentSeed);await remountOpponent()}
function syncCharacterSwitch(){$$('.character-switch [data-character]').forEach(b=>{const on=b.dataset.character===currentCharacterId;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))})}
function categoryForPart(part){return VARIANT_PART_CATEGORY[part]||part}
function selectionBucket(category){return SHARED_APPEARANCE_CATEGORIES.includes(category)?sharedAppearance:ownedAppearance[currentCharacterId]}
function selectedVariant(category){const key=variantKey(category);return key?selectionBucket(category)?.[key]??null:null}
function sanitizeVariantSelections(){if(!hasVariantContract(currentCharacterId))return;const normalized=playerAppearance();for(const category of SHARED_APPEARANCE_CATEGORIES){const key=variantKey(category);if(key)sharedAppearance[key]=normalized[key]??null}for(const category of CHARACTER_OWNED_CATEGORIES){const key=variantKey(category);if(key)ownedAppearance[currentCharacterId][key]=normalized[key]??null}appearanceColors[currentCharacterId]={...appearanceColors[currentCharacterId],...(normalized.colors||{})}}
function renderVariantOptions(){const rack=$('#variant-options');if(!rack)return;const options=variantOptions(currentCharacterId,activeAppearanceCategory);if(!options.length){rack.hidden=true;rack.innerHTML='';return}const active=selectedVariant(activeAppearanceCategory),baseLabel=CHARACTER_OWNED_CATEGORIES.includes(activeAppearanceCategory)?'БАЗА':'НЕТ';rack.hidden=false;rack.dataset.category=activeAppearanceCategory;rack.innerHTML=`<button data-variant="" class="${active==null?'active':''}">${baseLabel}</button>${options.map((id,i)=>`<button data-variant="${id}" class="${id===active?'active':''}">${String(i+1).padStart(2,'0')}</button>`).join('')}`;rack.querySelectorAll('[data-variant]').forEach(button=>button.addEventListener('click',()=>selectAppearanceVariant(activeAppearanceCategory,button.dataset.variant||null)))}
function syncAppearancePanel(){const appearance=playerAppearance();$$('[data-part]').forEach(b=>{const part=b.dataset.part,category=categoryForPart(part),options=variantOptions(currentCharacterId,category),usesVariants=options.length>0,on=usesVariants?selectedVariant(category)!=null:appearance[part]!==false;b.classList.toggle('active',on);b.classList.toggle('has-variants',usesVariants);b.setAttribute('aria-pressed',String(on));b.dataset.scope=SHARED_APPEARANCE_CATEGORIES.includes(category)?'shared':'owned';b.dataset.variantCount=String(options.length);if(usesVariants)b.setAttribute('aria-expanded',String(activeAppearanceCategory===category&&!$('#variant-options')?.hidden));else b.removeAttribute('aria-expanded')});renderVariantOptions()}
function commitAppearanceChange(){sanitizeVariantSelections();syncAppearancePanel();resetActors();renderPreview()}
function toggleAppearance(part){const category=categoryForPart(part),options=variantOptions(currentCharacterId,category);if(options.length){activeAppearanceCategory=category;syncAppearancePanel();return}if(!APPEARANCE_LAYERS.includes(part))return;if(SHARED_APPEARANCE_LAYERS.includes(part))sharedAppearance={...sharedAppearance,[part]:!sharedAppearance[part]};else if(CHARACTER_OWNED_LAYERS.includes(part))ownedAppearance={...ownedAppearance,[currentCharacterId]:{...ownedAppearance[currentCharacterId],[part]:!ownedAppearance[currentCharacterId][part]}};commitAppearanceChange()}
function selectAppearanceVariant(category,value){const key=variantKey(category),options=variantOptions(currentCharacterId,category);if(!key||!options.length)return;const next=value&&options.includes(value)?value:null;if(SHARED_APPEARANCE_CATEGORIES.includes(category))sharedAppearance={...sharedAppearance,[key]:next};else ownedAppearance={...ownedAppearance,[currentCharacterId]:{...ownedAppearance[currentCharacterId],[key]:next}};commitAppearanceChange()}
function resetAppearance(){sharedAppearance={hat:false,glasses:false,beard:false,accessory:false,...EMPTY_SHARED_VARIANTS()};ownedAppearance={...ownedAppearance,[currentCharacterId]:{outfit:true,shoes:true,...EMPTY_OWNED_VARIANTS()}};appearanceColors={...appearanceColors,[currentCharacterId]:EMPTY_COLORS()};commitAppearanceChange()}
async function chooseCharacter(id){if(id===currentCharacterId)return;currentCharacterId=id;sanitizeVariantSelections();await remountPlayerCharacter()}

function familyLabel(type){return NODE_SPECS[type]?.family||'NODE'}
function title(type){return NODE_SPECS[type]?.title||type}
function nodeValue(n){const f=familyLabel(n.type);if(f==='IMPULSE')return `W${n.p?.weight||1}`;if(n.type==='repeat')return `×${n.p?.count||1}`;if(f==='STATE')return `+${n.p?.delta??1}`;if(n.type==='ifbrain')return `>${n.p?.threshold||70}`;return ''}
function nodeSubtitle(n){return NODE_SPECS[n.type]?.description||familyLabel(n.type)}
function brainControl(n){const f=familyLabel(n?.type);if(f==='IMPULSE')return {key:'weight',min:1,max:5,step:1,label:'СИЛА ИМПУЛЬСА',format:v=>`W${v}`};if(n?.type==='repeat')return {key:'count',min:1,max:5,step:1,label:'СКОЛЬКО РАЗ',format:v=>`×${v}`};if(f==='STATE')return {key:'delta',min:1,max:5,step:1,label:'ИЗМЕНЕНИЕ ПАМЯТИ',format:v=>`+${v}`};if(n?.type==='ifbrain')return {key:'threshold',min:20,max:100,step:10,label:'ПОРОГ BRAIN',format:v=>`>${v}`};return null}
function brainNodeLocked(n){return Boolean(replayMode&&replayTargetNodeId&&n.id!==replayTargetNodeId)}
function currentValidation(){return brainValidation(currentBrainGraph,CRITICISM_IDEA_SCENARIO.openingTrigger)}
let brainEdgeSerial=0,brainControlSheet=null;
function markBrainEdgeKinds(graph){const order=graph.nodes.map(n=>n.id),index=new Map(order.map((id,i)=>[id,i]));graph.edges=graph.edges.map(edge=>{if(edge.uiKind)return edge;const a=index.get(edge.from),b=index.get(edge.to);return {...edge,uiKind:Number.isInteger(a)&&Number.isInteger(b)&&b===a+1?'primary':'extra'}});return graph}
function primaryEdgeId(from,to){return `brain-primary-${from}-${to}-${++brainEdgeSerial}`}
function rebuildBrainSequence(){markBrainEdgeKinds(currentBrainGraph);const manual=currentBrainGraph.edges.filter(e=>e.uiManual||e.uiKind==='extra').map(e=>({...e,uiManual:true})),manualByKey=new Map(manual.map(e=>[`${e.from}->${e.to}`,e])),usedManual=new Set(),primary=[];for(let i=0;i<currentBrainGraph.nodes.length-1;i++){const from=currentBrainGraph.nodes[i],to=currentBrainGraph.nodes[i+1],key=`${from.id}->${to.id}`,saved=manualByKey.get(key);if(saved){primary.push({...saved,uiKind:'primary'});usedManual.add(saved.id);continue}const working={...currentBrainGraph,edges:[...primary,...manual.filter(e=>!usedManual.has(e.id))]};if(canConnectNodes(working,from,to)){primary.push({id:primaryEdgeId(from.id,to.id),from:from.id,to:to.id,uiKind:'primary'})}}const extras=manual.filter(e=>!usedManual.has(e.id)).map(e=>({...e,uiKind:'extra'}));currentBrainGraph.edges=[...primary,...extras];currentBrainGraph.nodes.forEach((node,i)=>{node.ui={...(node.ui||{}),x:0,y:i*82}})}
function normalizeBrainStack(){markBrainEdgeKinds(currentBrainGraph);currentBrainGraph.nodes.forEach((node,i)=>{node.ui={...(node.ui||{}),x:0,y:i*82}})}
function renderBrainPresets(){const host=$('#brain-presets');if(!host)return;host.hidden=replayMode;host.innerHTML=BRAIN_PRESETS.map(p=>`<button type="button" data-brain-preset="${p.id}" class="${activeBrainPresetId===p.id?'active':''}">${p.label}</button>`).join('')+`<button type="button" data-brain-preset="custom" class="${activeBrainPresetId==='custom'?'active':''}">СОБРАТЬ СВОЮ КАТАСТРОФУ</button>`;host.querySelectorAll('[data-brain-preset]').forEach(b=>b.addEventListener('click',()=>applyBrainPreset(b.dataset.brainPreset)))}
function applyBrainPreset(id){if(replayMode)return;const p=brainPreset(id);currentBrainGraph=cloneBrainGraph(p?.graph||BLANK_BRAIN);normalizeBrainStack();activeBrainPresetId=p?.id||'custom';activeBrainNodeId=null;brainConnectFromId=null;closeBrainControlSheet();renderBrain()}
function brainActionWidth(n){return brainControl(n)?184:128}
function brainNodeHtml(n){const selected=n.id===activeBrainNodeId,source=n.id===brainConnectFromId,locked=brainNodeLocked(n),validTargets=brainConnectFromId?compatibleBrainTargets(currentBrainGraph,brainConnectFromId):[],compatible=validTargets.includes(n.id),control=brainControl(n);return `<article class="brain-stack-node ${selected?'open':''} ${source?'connection-source':''} ${compatible?'connection-target':''} ${locked?'locked':''}" data-brain-node-wrap="${n.id}" style="--brain-actions-w:${brainActionWidth(n)}px"><div class="brain-stack-card"><div class="brain-stack-actions"><button type="button" class="brain-stack-action ${source?'active':''}" data-brain-connect="${n.id}" aria-label="Связать"><img src="./assets/ui/brain-connect.svg" alt=""></button>${control?`<button type="button" class="brain-stack-action" data-brain-param="${n.id}">${nodeValue(n)}</button>`:''}<button type="button" class="brain-stack-action" data-brain-delete="${n.id}" aria-label="Удалить"><img src="./assets/ui/brain-trash.svg" alt=""></button></div><button type="button" class="brain-stack-main" data-brain-node="${n.id}" ${locked?'aria-disabled="true"':''}><span class="brain-stack-family">${familyLabel(n.type).toLowerCase()}</span><strong class="brain-stack-title">${title(n.type)}</strong><span class="brain-stack-subtitle">${nodeSubtitle(n)}</span></button>${control?`<span class="brain-stack-value">${nodeValue(n)}</span>`:''}<button type="button" class="brain-stack-drag" data-brain-drag="${n.id}" aria-label="Перетянуть"><span class="brain-stack-handle"></span></button><button type="button" class="brain-stack-connect-target" data-brain-target="${n.id}">СОЕДИНИТЬ</button></div></article>`}
function brainEdgeRoutes(){const order=currentBrainGraph.nodes.map(n=>n.id),index=new Map(order.map((id,i)=>[id,i]));const routes=currentBrainGraph.edges.map((edge,orderIndex)=>{const fromIndex=index.get(edge.from),toIndex=index.get(edge.to);return {...edge,orderIndex,fromIndex,toIndex,a:Math.min(fromIndex,toIndex),b:Math.max(fromIndex,toIndex),kind:edge.uiKind==='extra'?'extra':'primary'}}).filter(e=>Number.isInteger(e.fromIndex)&&Number.isInteger(e.toIndex));const extras=routes.filter(e=>e.kind==='extra').sort((a,b)=>(a.a-b.a)||(a.b-b.b)||(a.orderIndex-b.orderIndex));const lanes=[];extras.forEach(edge=>{let lane=0;while(lanes[lane]?.some(other=>Math.max(edge.a,other.a)<Math.min(edge.b,other.b)))lane++;(lanes[lane]??=[]).push(edge);edge.lane=lane});return routes}
function drawBrainEdges(){const host=$('#brain-graph'),svg=host?.querySelector('.brain-stack-links');if(!host||!svg)return;const box=host.getBoundingClientRect(),byId=Object.fromEntries($$('#brain-graph [data-brain-node-wrap]').map(el=>[el.dataset.brainNodeWrap,el]));const routes=brainEdgeRoutes(),outgoing=new Map(),incoming=new Map();routes.forEach(edge=>{(outgoing.get(edge.from)??outgoing.set(edge.from,[]).get(edge.from)).push(edge);(incoming.get(edge.to)??incoming.set(edge.to,[]).get(edge.to)).push(edge)});outgoing.forEach(list=>list.sort((a,b)=>(a.kind!==b.kind?(a.kind==='primary'?-1:1):a.toIndex-b.toIndex)));incoming.forEach(list=>list.sort((a,b)=>(a.kind!==b.kind?(a.kind==='primary'?-1:1):a.fromIndex-b.fromIndex)));svg.setAttribute('viewBox',`0 0 ${host.clientWidth} ${Math.max(host.scrollHeight,host.clientHeight)}`);svg.innerHTML=routes.map(edge=>{const from=byId[edge.from],to=byId[edge.to];if(!from||!to)return '';const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),out=outgoing.get(edge.from)||[edge],inc=incoming.get(edge.to)||[edge],slot=9,y1=a.top+a.height/2-box.top+(out.indexOf(edge)-(out.length-1)/2)*slot,y2=b.top+b.height/2-box.top+(inc.indexOf(edge)-(inc.length-1)/2)*slot,cardX=a.left-box.left,laneX=edge.kind==='primary'?Math.max(8,cardX-14):Math.max(8,cardX-32-(edge.lane||0)*13);return `<path class="brain-stack-edge ${edge.kind==='extra'?'extra':''}" data-edge="${edge.id}" d="M ${cardX} ${y1} H ${laneX} V ${y2} H ${cardX}"></path>`}).join('')}
function reorderBrainNode(id,targetIndex){const from=currentBrainGraph.nodes.findIndex(n=>n.id===id);if(from<0||targetIndex===from)return;const [node]=currentBrainGraph.nodes.splice(from,1),bounded=Math.max(0,Math.min(currentBrainGraph.nodes.length,targetIndex));currentBrainGraph.nodes.splice(bounded,0,node);rebuildBrainSequence();activeBrainPresetId='custom'}
function bindBrainStackDrag(){$$('#brain-graph [data-brain-drag]').forEach(handle=>{let start=null;handle.addEventListener('pointerdown',e=>{const id=handle.dataset.brainDrag,node=currentBrainGraph.nodes.find(n=>n.id===id);if(replayMode||brainNodeLocked(node))return;const wrap=handle.closest('.brain-stack-node');start={id,y:e.clientY,index:currentBrainGraph.nodes.findIndex(n=>n.id===id),wrap};handle.setPointerCapture?.(e.pointerId);e.preventDefault()});handle.addEventListener('pointermove',e=>{if(!start)return;start.wrap.style.transform=`translateY(${e.clientY-start.y}px)`;requestAnimationFrame(drawBrainEdges)});handle.addEventListener('pointerup',e=>{if(!start)return;const wraps=$$('#brain-graph .brain-stack-node').filter(w=>w!==start.wrap);let target=wraps.filter(w=>e.clientY>w.getBoundingClientRect().top+w.getBoundingClientRect().height/2).length;reorderBrainNode(start.id,target);start=null;renderBrain()});handle.addEventListener('pointercancel',()=>{if(start){start.wrap.style.transform='';start=null;renderBrainCanvas()}})})}
function selectBrainNode(id){const node=currentBrainGraph.nodes.find(n=>n.id===id);if(!node||brainNodeLocked(node))return;brainConnectFromId=null;activeBrainNodeId=activeBrainNodeId===id?null:id;renderBrainCanvas();renderBrainStatus()}
function beginBrainConnection(id){if(replayMode)return;brainConnectFromId=brainConnectFromId===id?null:id;activeBrainNodeId=id;renderBrainCanvas();renderBrainStatus()}
function finishBrainConnection(id){if(replayMode||!brainConnectFromId)return;const made=connectBrainNodes(currentBrainGraph,brainConnectFromId,id);if(made){made.uiKind='extra';made.uiManual=true;brainConnectFromId=null;activeBrainNodeId=null;activeBrainPresetId='custom'}renderBrainCanvas();renderBrainStatus()}
function deleteBrainNode(id){if(replayMode)return;removeBrainNode(currentBrainGraph,id);activeBrainNodeId=null;brainConnectFromId=null;activeBrainPresetId='custom';rebuildBrainSequence();renderBrain()}
function closeBrainControlSheet(){brainControlSheet?.remove();brainControlSheet=null}
function showBrainControlSheet(id){const node=currentBrainGraph.nodes.find(n=>n.id===id),control=brainControl(node);if(!node||!control||brainNodeLocked(node))return;closeBrainControlSheet();const current=Number(node.p?.[control.key]??control.min),sheet=document.createElement('div');sheet.className='brain-control-backdrop';const ticks=Math.max(2,Math.round((control.max-control.min)/(control.step||1))+1);sheet.innerHTML=`<section class="brain-control-sheet"><div class="brain-control-sheet__handle"></div><div class="brain-control-sheet__head"><b>${title(node.type)}</b><span>${control.label}</span></div><div class="brain-control-range"><div class="brain-control-range__inner" role="slider" tabindex="0" aria-valuemin="${control.min}" aria-valuemax="${control.max}" aria-valuenow="${current}"><div class="brain-control-range__track"></div><div class="brain-control-range__ticks">${Array.from({length:Math.min(ticks,9)},()=>'<i></i>').join('')}</div><button type="button" class="brain-control-range__thumb">${current}</button></div></div><div class="brain-control-range__note">${nodeSubtitle(node)}</div></section>`;document.body.appendChild(sheet);brainControlSheet=sheet;const range=sheet.querySelector('.brain-control-range__inner'),thumb=sheet.querySelector('.brain-control-range__thumb'),snap=value=>Math.max(control.min,Math.min(control.max,control.min+Math.round((value-control.min)/(control.step||1))*(control.step||1))),place=value=>{const v=snap(value),pct=(v-control.min)/(control.max-control.min||1),radius=34,usable=Math.max(0,range.clientWidth-radius*2),x=radius+pct*usable;thumb.style.left=`${x}px`;thumb.textContent=String(v);range.setAttribute('aria-valuenow',String(v));node.p[control.key]=v;activeBrainPresetId='custom'},fromX=x=>{const r=range.getBoundingClientRect(),radius=34,left=r.left+radius,right=r.right-radius,pct=(Math.max(left,Math.min(right,x))-left)/(right-left||1);return control.min+pct*(control.max-control.min)};requestAnimationFrame(()=>place(current));let dragging=false;thumb.addEventListener('pointerdown',e=>{dragging=true;thumb.setPointerCapture?.(e.pointerId);e.preventDefault()});thumb.addEventListener('pointermove',e=>{if(!dragging)return;place(fromX(e.clientX));renderBrainCanvas()});thumb.addEventListener('pointerup',()=>{dragging=false});thumb.addEventListener('pointercancel',()=>{dragging=false});range.addEventListener('pointerdown',e=>{if(e.target===thumb)return;place(fromX(e.clientX));renderBrainCanvas()});range.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();place(Number(node.p[control.key])+(e.key==='ArrowRight'?1:-1)*(control.step||1));renderBrainCanvas()});sheet.addEventListener('click',e=>{if(e.target===sheet)closeBrainControlSheet()})}
function renderBrainStatus(){const host=$('#brain-validation');if(!host)return;const v=currentValidation();host.dataset.code=v.code;host.classList.toggle('ready',v.runnable);host.textContent=brainConnectFromId?`СВЯЗЬ: «${title(currentBrainGraph.nodes.find(n=>n.id===brainConnectFromId)?.type)}» → ВЫБЕРИ ДОПУСТИМЫЙ УЗЕЛ.`:(v.runnable?'ГОТОВ. ГРАФ ДОХОДИТ ДО РЕАКЦИИ.':v.detail);$('#to-setup').disabled=!v.runnable}
function renderBrainCanvas(){const host=$('#brain-graph');if(!host)return;normalizeBrainStack();host.dataset.edgeCount=String(currentBrainGraph.edges.length);host.dataset.connectFrom=brainConnectFromId||'';host.innerHTML=`<svg class="brain-stack-links" aria-hidden="true"></svg><div class="brain-stack-list">${currentBrainGraph.nodes.map(brainNodeHtml).join('')}</div>`;host.querySelectorAll('[data-brain-node]').forEach(button=>button.addEventListener('click',()=>selectBrainNode(button.dataset.brainNode)));host.querySelectorAll('[data-brain-connect]').forEach(button=>button.addEventListener('click',e=>{e.stopPropagation();beginBrainConnection(button.dataset.brainConnect)}));host.querySelectorAll('[data-brain-param]').forEach(button=>button.addEventListener('click',e=>{e.stopPropagation();showBrainControlSheet(button.dataset.brainParam)}));host.querySelectorAll('[data-brain-delete]').forEach(button=>button.addEventListener('click',e=>{e.stopPropagation();deleteBrainNode(button.dataset.brainDelete)}));host.querySelectorAll('[data-brain-target]').forEach(button=>button.addEventListener('click',e=>{e.stopPropagation();finishBrainConnection(button.dataset.brainTarget)}));bindBrainStackDrag();requestAnimationFrame(drawBrainEdges)}
function showNodeLibrary(){if(replayMode)return;overlay.innerHTML=`<div class="overlay-card brain-library"><p class="kicker">БИБЛИОТЕКА</p><h3>ДОБАВИТЬ УЗЕЛ</h3>${BRAIN_FAMILY_ORDER.map(f=>`<section><strong>${f}</strong><div>${familyNodes(f).filter(n=>n.availableInSlice!==false).filter(n=>n.family!=='TRIGGER'||n.type===CRITICISM_IDEA_SCENARIO.openingTrigger).map(n=>`<button type="button" data-add-brain-node="${n.type}"><small>${f}</small><strong>${n.title}</strong><span>${nodeSubtitle({type:n.type})}</span></button>`).join('')}</div></section>`).join('')}<button class="secondary-reset" id="close-overlay">ЗАКРЫТЬ</button></div>`;overlay.hidden=false;overlay.querySelectorAll('[data-add-brain-node]').forEach(b=>b.addEventListener('click',()=>{const node=addBrainNode(currentBrainGraph,b.dataset.addBrainNode);activeBrainNodeId=node.id;activeBrainPresetId='custom';brainConnectFromId=null;rebuildBrainSequence();hideOverlay();renderBrain();requestAnimationFrame(()=>document.querySelector(`[data-brain-node-wrap="${CSS.escape(node.id)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}))}));$('#close-overlay').onclick=hideOverlay}
function renderBrain(){closeBrainControlSheet();normalizeBrainStack();renderBrainPresets();renderBrainCanvas();renderBrainStatus();const add=$('#brain-add-node');if(add)add.hidden=replayMode}
function brainSnapshot(){return cloneBrainGraph(currentBrainGraph)}
function restoreBrainSnapshot(graph){currentBrainGraph=cloneBrainGraph(graph);ensureBrainPositions(currentBrainGraph);activeBrainNodeId=null;brainConnectFromId=null}

function metricRow(label,key){const a=controller?.encounter?.actors.A.state[key]??actors.A.state[key],b=controller?.encounter?.actors.B.state[key]??actors.B.state[key];const danger=(key==='brain'&&(a>=85||b>=85))||(key==='energy'&&(a<=25||b<=25))||(key==='contact'&&(a<=20||b<=20))||(key==='tension'&&(a>=85||b>=85));return `<div class="metric ${danger?'danger':''}"><label>${label}</label><span class="bar"><i style="width:${Math.max(0,Math.min(100,a))}%"></i></span><span class="n">${Math.round(a)}</span><span class="n">${Math.round(b)}</span><span class="bar"><i style="width:${Math.max(0,Math.min(100,b))}%"></i></span></div>`}
function renderTalk(){if(!controller?.encounter)return;const e=controller.encounter;$('#turn').textContent=e.turn;$('#actor-a-name').textContent=e.actors.A.name.toUpperCase();$('#actor-b-name').textContent=e.actors.B.name.toUpperCase();$('#metrics').innerHTML=metricRow('ENERGY','energy')+metricRow('BRAIN','brain')+metricRow('TENSION','tension')+metricRow('CONTACT','contact');const transcript=e.transcript.slice(-5);$('#dialogue').innerHTML=transcript.length?transcript.map(x=>`<div class="bubble ${x.actorId==='A'?'a':'b'}"><small>${e.actors[x.actorId].name.toUpperCase()}</small>${x.phrase||'…'}</div>`).join(''):'<p class="empty">Никто ещё ничего не сказал.</p>';$('#next-turn').textContent=mode==='auto'?(autoTimer?'PAUSE':'RESUME'):'NEXT TURN →'}
function renderDelta(trace){if(!trace)return $('#delta').textContent='';const d=trace.metricDeltas.self,m=trace.memoryChanges?.[0];const parts=Object.entries(d).filter(([,v])=>v).map(([k,v])=>`${k.toUpperCase()} ${v>0?'+':''}${Number(v.toFixed?.(1)??v)}`);if(m)parts.unshift(`${String(m.key).toUpperCase()} ${m.before}→${m.after}`);const line=parts.join(' · ');$('#delta').textContent=line;setTimeout(()=>{if($('#delta').textContent===line)$('#delta').textContent=''},1100)}
function makeController(){const specA=characterSpec(currentCharacterId),specB=characterSpec(opponentProfile.baseCharacterId);const rendererA=new CharacterRenderer({side:'A',root:$('#actor-a'),rigFallback:specA.rigFallback}),rendererB=new CharacterRenderer({side:'B',root:$('#actor-b'),rigFallback:specB.rigFallback});controller=new VerticalSliceController({scenario:CRITICISM_IDEA_SCENARIO,actors,renderers:{A:rendererA,B:rendererB},onEvent:handleEvent})}
function handleEvent(evt){if(evt.type==='TURN'){renderDelta(evt.trace);renderTalk()}if(evt.type==='HOT_PATCH'){stopAuto();showHotPatch(evt.breakpoint)}if(evt.type==='RESULT'){stopAuto();showResult(evt.result)}if(evt.type==='PATCH'){hideOverlay();renderTalk();if(mode==='auto')startAuto()}}
function doNext(){if(!controller?.encounter||controller.encounter.result)return;const out=controller.next();renderTalk();if(out?.result)showResult(controller.result())}
function startAuto(){stopAuto();autoTimer=setInterval(()=>{if(controller?.encounter?.status==='HOT_PATCH'||controller?.encounter?.result)return stopAuto();doNext()},850);renderTalk()}
function stopAuto(){if(autoTimer){clearInterval(autoTimer);autoTimer=null}if(controller?.encounter)renderTalk()}
function hotPatchChainEdges(actor,ids){const set=new Set(ids||[]);return actor.brainGraph.edges.filter(e=>set.has(e.from)&&set.has(e.to))}
function hotPatchRewireOptions(actor,edge){if(!edge)return [];const graph=actor.brainGraph,from=graph.nodes.find(n=>n.id===edge.from),without={...graph,edges:graph.edges.filter(e=>e.id!==edge.id)};return graph.nodes.filter(candidate=>candidate.id!==edge.to&&canConnectNodes(without,from,candidate)).filter(candidate=>{const probe=cloneBrainGraph(graph),probeEdge=probe.edges.find(e=>e.id===edge.id);probeEdge.to=candidate.id;return brainValidation(probe,CRITICISM_IDEA_SCENARIO.openingTrigger).runnable})}
function showRewirePatch(bp,edge){const actor=controller.encounter.actors[bp.actorId],options=hotPatchRewireOptions(actor,edge);overlay.innerHTML=`<div class="overlay-card"><p class="kicker">HOT PATCH / СВЯЗЬ</p><h3>КУДА ПЕРЕНАПРАВИТЬ?</h3><p>${title(actor.brainGraph.nodes.find(n=>n.id===edge.from)?.type)} → …</p><div class="patch-grid">${options.map(n=>`<button data-rewire-target="${n.id}">→ ${title(n.type)}</button>`).join('')}<button data-rewire-back>НАЗАД</button></div></div>`;overlay.hidden=false;overlay.querySelectorAll('[data-rewire-target]').forEach(button=>button.addEventListener('click',()=>controller.patch({kind:'rewire',actorId:bp.actorId,edgeId:edge.id,toNodeId:button.dataset.rewireTarget})));overlay.querySelector('[data-rewire-back]')?.addEventListener('click',()=>showHotPatch(bp))}
function showHotPatch(bp){const actor=controller.encounter.actors[bp.actorId],ids=bp.nodeIds||[],chain=ids.map(id=>title(actor.brainGraph.nodes.find(n=>n.id===id)?.type)).join(' → '),repeat=ids.map(id=>actor.brainGraph.nodes.find(n=>n.id===id)).find(n=>n?.type==='repeat'),impulse=ids.map(id=>actor.brainGraph.nodes.find(n=>n.id===id)).find(n=>familyLabel(n?.type)==='IMPULSE'),chainEdges=hotPatchChainEdges(actor,ids),pauseEdge=chainEdges.find(e=>familyLabel(actor.brainGraph.nodes.find(n=>n.id===e.from)?.type)==='IMPULSE'&&familyLabel(actor.brainGraph.nodes.find(n=>n.id===e.to)?.type)==='REACTION')||chainEdges.find(e=>familyLabel(actor.brainGraph.nodes.find(n=>n.id===e.to)?.type)==='REACTION'),rewireEdge=chainEdges.find(e=>hotPatchRewireOptions(actor,e).length);overlay.innerHTML=`<div class="overlay-card"><p class="kicker">HOT PATCH</p><h3>МОЗГ НАГРЕВАЕТСЯ.</h3><p>Сейчас эта цепочка собирается сделать хуже. Один патч — потом продолжаем тот же разговор.</p><div class="chain">${chain}</div><div class="patch-grid">${repeat?`<button data-patch="repeat">REPEAT ×${repeat.p.count} → ×${Math.max(1,repeat.p.count-1)}</button>`:''}${impulse?`<button data-patch="impulse">${title(impulse.type)} ${impulse.p.weight} → ${Math.max(1,impulse.p.weight-1)}</button>`:''}${pauseEdge?'<button data-patch="pause">ВСТАВИТЬ ПАУЗУ</button>':''}${rewireEdge?'<button data-patch="rewire">СМЕНИТЬ СВЯЗЬ</button>':''}<button data-patch="skip">НИЧЕГО НЕ ТРОГАТЬ</button></div></div>`;overlay.hidden=false;$('[data-patch=repeat]')?.addEventListener('click',()=>controller.patch({kind:'reduce-repeat',actorId:bp.actorId,nodeId:repeat.id}));$('[data-patch=impulse]')?.addEventListener('click',()=>controller.patch({kind:'reduce-impulse',actorId:bp.actorId,nodeId:impulse.id}));$('[data-patch=pause]')?.addEventListener('click',()=>controller.patch({kind:'insert-pause',actorId:bp.actorId,edgeId:pauseEdge.id,nodeId:`pause-${controller.encounter.turn}-${bp.actorId}`}));$('[data-patch=rewire]')?.addEventListener('click',()=>showRewirePatch(bp,rewireEdge));$('[data-patch=skip]').addEventListener('click',()=>{controller.declinePatch();hideOverlay();if(mode==='auto')startAuto()})}
function showTrace(){const trace=controller?.encounter?.traces.at(-1);if(!trace)return;overlay.innerHTML=`<div class="overlay-card"><p class="kicker">TRACE</p><h3>ПОЧЕМУ ЭТО СЛУЧИЛОСЬ?</h3><div class="trace-list">TRIGGER: ${trace.trigger}\nPATH: ${trace.visitedNodes.join(' → ')}\nIMPULSE: ${trace.selectedImpulse}\nREACTION: ${trace.selectedReaction}\nLOOPS: ${trace.loops}\nMEMORY: ${(trace.memoryChanges||[]).map(m=>`${m.key} ${m.before}→${m.after}`).join(', ')||'—'}</div><button class="primary" id="close-overlay">ЗАКРЫТЬ</button></div>`;overlay.hidden=false;$('#close-overlay').onclick=hideOverlay}
function hideOverlay(){overlay.hidden=true;overlay.innerHTML=''}
function comparisonHtml(c){const fmt=v=>`${v>0?'+':''}${v}`;return `<small>БЫЛО / СТАЛО</small><strong>${c.sameScenario?'ТОТ ЖЕ СЦЕНАРИЙ':'СЦЕНАРИЙ ИЗМЕНИЛСЯ'}</strong><div class="compare-grid"><span>BRAIN ${fmt(c.metrics.brain)}</span><span>TENSION ${fmt(c.metrics.tension)}</span><span>CONTACT ${fmt(c.metrics.contact)}</span><span>ENERGY ${fmt(c.metrics.energy)}</span></div>`}
function showResult(result){show('result');$('#result-title').textContent=result.punchline;$('#result-cause').textContent=result.stageB.cause;$('#result-node').textContent=result.stageC.nodeType?title(result.stageC.nodeType):'—';if(!baselineEncounter){baselineEncounter=structuredClone(controller.encounter);replayTargetNodeId=result.stageC.nodeId||null;$('#comparison').hidden=true;$('#rerun').textContent='ИЗМЕНИТЬ ОДНУ ВЕЩЬ →'}else if(replayMode){const c=compareRuns(baselineEncounter,controller.encounter);$('#comparison').innerHTML=comparisonHtml(c);$('#comparison').hidden=false;$('#rerun').textContent='ЕЩЁ ОДИН ЭКСПЕРИМЕНТ →'}}
function prepareReplay(){replayMode=true;playerName=firstRunConfig?.playerName||playerName;syncPlayerName();currentCharacterId=firstRunConfig?.characterId||currentCharacterId;sharedAppearance={...(firstRunConfig?.sharedAppearance||sharedAppearance)};ownedAppearance=structuredClone(firstRunConfig?.ownedAppearance||ownedAppearance);appearanceColors=structuredClone(firstRunConfig?.appearanceColors||appearanceColors);opponentSeed=firstRunConfig.opponentSeed;opponentProfile=structuredClone(firstRunConfig.opponentProfile);restoreBrainSnapshot(firstRunConfig.brainGraph);controller=null;const targetNode=currentBrainGraph.nodes.find(n=>n.id===replayTargetNodeId);$('#replay-note').textContent=`КОНТРФАКТ: МЕНЯЕМ ТОЛЬКО «${title(targetNode?.type||'repeat')}». СОПЕРНИК ТОТ ЖЕ.`;show('brain')}
$('#player-name')?.addEventListener('input',e=>setPlayerName(e.target.value));$$('.character-switch [data-character]').forEach(b=>b.addEventListener('click',()=>chooseCharacter(b.dataset.character)));$$('[data-part]').forEach(b=>b.addEventListener('click',()=>toggleAppearance(b.dataset.part)));$('#appearance-reset').onclick=resetAppearance;$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b))}));$$('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.nav==='talk'&&!controller?.encounter)return;show(b.dataset.nav)}));$('#to-brain').onclick=()=>{resetActors();show('brain')};$('#to-setup').onclick=()=>show('setup');$('#brain-add-node').onclick=showNodeLibrary;$('#reroll-opponent').onclick=rerollOpponent;$('#play').onclick=()=>{if(!replayMode&&!firstRunConfig)firstRunConfig={brainGraph:brainSnapshot(),playerName:playerDisplayName(),characterId:currentCharacterId,sharedAppearance:{...sharedAppearance},ownedAppearance:structuredClone(ownedAppearance),appearanceColors:structuredClone(appearanceColors),mode,opponentSeed,opponentProfile:structuredClone(opponentProfile)};resetActors();makeController();controller.start({mode});show('talk');if(mode==='auto')startAuto()};$('#next-turn').onclick=()=>{if(mode==='auto'){autoTimer?stopAuto():startAuto()}else doNext()};$('#trace-btn').onclick=showTrace;$('#rerun').onclick=async()=>{if(!baselineEncounter)return;if(replayMode){baselineEncounter=null;firstRunConfig=null;replayTargetNodeId=null;replayMode=false;opponentSeed=explicitSeed||freshOpponentSeed();opponentProfile=createOpponentProfile(opponentSeed);await remountOpponent();controller=null;show('brain')}else prepareReplay()};overlay.addEventListener('click',e=>{if(e.target===overlay)hideOverlay()});window.addEventListener('resize',()=>{if(app.dataset.screen==='brain')requestAnimationFrame(drawBrainEdges)});
resetActors();syncPlayerName();syncCharacterSwitch();await mountCharacterAssets();renderScenarioCopy();show('person');
